### ISSUE TITLE
Demo version uses V2.0.

### ISSUE THREAD

**Issue by toplisek** [woothemes/FlexSlider#1008]
There is old demo version as it uses V2.0. Can you manage updated demo version?

**Comment by jeffikus** [comment]
@mattyza can we get this updated on woo.com once I've deployed 2.4.0 please?

**Comment by jeffikus** [comment]
I want to have WooSlider and FlexSlider lined up on Monday - so all of them are running the same. I'll ping you when I'm ready to roll out.

**Comment by mattyza** [comment]
Resolved in the latest release! :)
