### ISSUE TITLE
2.2.2 .min version does not include latest changes

### ISSUE THREAD

**Issue by illepic** [woothemes/FlexSlider#1015]
There are fixes in the non min version of 2.2.2  that do not show in the min version. Case in point: This ticket: https://github.com/woothemes/FlexSlider/issues/292 is fixed in jquery.flexslider.js but not in jquery.flexslider-min.js.

Do note that this is in reference to the .zip file pulled down directly from http://www.woothemes.com/flexslider/, which I'm assuming is from this repo.

**Comment by mattyza** [comment]
Hi @illepic.

This has been resolved in the latest version of FlexSlider, available here: http://github.com/woothemes/flexslider/releases/latest/.

Thanks! :)
