### ISSUE TITLE
Documentation and Tutorials

### ISSUE THREAD

**Issue by debugger22** [woothemes/FlexSlider#1020]
There is a lack of proper documentation about the working of this library. Even tutorial code is not complete. Please give options to download complete tutorial code.

**Comment by mattyza** [comment]
Hi @debugger22.

Thanks for your feedback.

We've provided documentation at http://woothemes.com/flexslider/.

If this documentation isn't sufficient, please let us know the kinds of documentation and tutorials you're looking for.

Thanks. :)

**Comment by debugger22** [comment]
:+1:
