### ISSUE TITLE
Clicks that don't "click"

### ISSUE THREAD

**Issue by koenpopma** [woothemes/FlexSlider#1034]
Hi there,

I use your Flex Slider script for a long time, with great pleasure. But at this moment the "click" does not work, both (the arrows and the bullets) don't work properly. On the (touch) devices it works just fine.

Tested on Mac // Firefox 26.0 // jQuery FlexSlider v2.0

Can you take a look at that?

**Comment by jeffikus** [comment]
Hi there

I've just tested in 2.3.0 and this is working, please reopen if you are experiencing something else.

Thanks,
