### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by LeBaux** [woothemes/FlexSlider#1041]
Hi there. I am using flexslider for a fullscreen popup. But on a certain resolutions, there is way to close the popup, because the "grey" clickable area that closes the slider is too small, especially on 4:3 desktops. Is there a option to implement "esc" and "closenav" - button closing the popup?

OK resolution:
![fullscreen](https://f.cloud.github.com/assets/5657511/2348226/7102011a-a555-11e3-8192-d1e11b6b11b5.gif)

Not-so-OK resolution:
![smallscreen](https://f.cloud.github.com/assets/5657511/2348323/5c0dedd6-a556-11e3-8f1e-839658adbd9d.gif)

I have in HTML template.
http://www.ansonika.com/bed-and-breakfast/
Just click on any "room".
Thanks for any information!

**Comment by jeffikus** [comment]
Hi there

I would just add a keypress event in jquery for the esc key and close the popup that way, not sure what you are using to load the popup, but in the keypress event just call the close function. 

More on keypress events in jquery -> http://api.jquery.com/keydown/ as far as im aware, esc is keydown 27.
