### ISSUE TITLE
maximize slider to full screen

### ISSUE THREAD

**Issue by mastef** [woothemes/FlexSlider#1065]
Hi guys, maybe I've missed something as most 'full screen' related issues are actually referring to a full-width background slider embedded in the page.

I'm looking for a way to add a button that can maximize the slider to full screen, such as seen here : http://www.ign.com/articles/2014/03/18/why-pixel-art-is-totally-awesome ( hover over the image/slider in section "Modern Indie Pixels" - a button to make the slider fullscreen will show up in the top right corner )

Is this currently supported with FlexSlider?

Use cases :
Mobile
When user watches the slides on mobile, pressing the 'full screen' hover, would maximize the slides on the viewport and - if possible - remove the browser controls. ( Like maximizing a youtube video )

Desktop
When pressing the fullscreen button, the browser controls would disappear, like in the youtube fullscreen mode, and the slider would take care of the full screen. Pressing ESC or same hover over button would switch back to normal page view.

**Comment by mattyza** [comment]
Hi @mastef.

To do this, you'd need to add a button via HTML (or via JavaScript) and bind an event on `click` of that button, which swaps out a CSS class on your slideshow container.

That CSS class should style the slideshow container as being full screen. FlexSlider would then respond to the width of it's container, as FlexSlider is responsive.

You can then call the `init` method on your FlexSlider instance, to re-instantiate the slideshow.

I hope this helps! :)
