### ISSUE TITLE
How To Use FlexSlider  With Asp.net MVC4

### ISSUE THREAD

**Issue by alimd110** [woothemes/FlexSlider#1066]
Hi ,all

i am using FlexSlider  in mvc4 asp.net but dos not show image 

this is My FlexSliderHelper:
 private List<FlexSliderItem> models = null;
public class FlexSliderHelper
    {

   public FlexSliderHelper( List<FlexSliderItem> _models)
        {
              models = _models;
        }
        public IHtmlString GetHtml()
        {
            const string style = "flexslider";
            const string style1 = "slides";
            var sb = new StringBuilder();
            sb.AppendLine("<div id='event-slider' class='"+ style + "'>");
            sb.AppendLine("<ul class='" + style1 + "'>");
            sb.AppendLine("<li>");
            foreach (var model in models)
            {
                string img = string.Format("<img src='{0}' alt='{1}' title='{2}' />", model.ImageFilePath, "",
                                           model.Caption);
                string item = "";
                if (model.LinkUrl.Trim().Length > 0 &&
                    Uri.IsWellFormedUriString(model.LinkUrl, UriKind.RelativeOrAbsolute))
                {
                    item = string.Format("<a href='{0}'>{1}</a>", model.LinkUrl, img);
                }
                else
                {
                    item = img;
                }
                sb.AppendLine(item);
            }
            sb.AppendLine("</div>");
            sb.AppendLine("</li>");
            sb.AppendLine("</ul>");
            sb.AppendLine("<script type='text/javascript'>");
            //sb.AppendLine("$('#" + _id + "').parent().ready(function () {");  
            sb.Append("$(document).ready(function(){");
            sb.AppendLine("$('.flexslider').flexslider({ animation: 'slide'});");
            //sb.AppendLine("$('.nivo-controlNav a').empty();");//semi hack for rtl layout    
            //sb.AppendLine("$('#" + _id + "').nivoSlider();");   
            sb.AppendLine("});");
            sb.AppendLine("</script>");
            return new HtmlString(sb.ToString());

        }

    }
    public class FlexSliderItem
    {
        public string ImageFilePath { get; set; }
        public string Caption { get; set; }
        public string LinkUrl { get; set; }
    }

    }

This is My PartialView

@using Mvc4.Helper
@model List<FlexSliderItem>
@{
    var news = new FlexSliderHelper(Model.ToList());
}
@news.GetHtml()

This is My Controller
  public virtual ActionResult FlexSlider()
        {
            var models = new List<FlexSliderItem>
            {
                new FlexSliderItem()
                {
                    ImageFilePath = Url.Content("~/Images/News/10.jpg"),
                    Caption = "",
                    LinkUrl = "http://www.google.com",
                },
                new FlexSliderItem()
                {
                    ImageFilePath = Url.Content("~/Images/News/11.jpg"),
                    Caption = "#htmlcaption",
                    LinkUrl = "",
                },
                new FlexSliderItem()
                {
                    ImageFilePath = Url.Content("~/Images/News/12.jpg"),
                    Caption = "",
                    LinkUrl = "",
                },
                new FlexSliderItem()
                {
                    ImageFilePath = Url.Content("~/Images/News/8.jpg"),
                    Caption = "",
                    LinkUrl = "",
                },
                new FlexSliderItem()
                {
                    ImageFilePath = Url.Content("~/Images/News/7.jpg"),
                    Caption = "My Title",
                    LinkUrl = "",
                }
            };
            return PartialView("_NewsSliderPartial", models);
        }

And My View
   <div class="panel-body shadow-small">
                           
                            @{
                               Html.RenderAction("FlexSlider", "Home");
                            }
                         
                        </div>

how to Resolve this problem?
please submit example
thank you

**Comment by mattyza** [comment]
I can echo @kirkov 's comment, here.

Please ensure your HTML output is the same as the demo files provided, and that there are no JavaScript errors once your page has loaded. JavaScript errors can be caused by any JavaScript loaded on the page, so another JavaScript you may have running may be causing FlexSlider to load incorrectly as well.
