### ISSUE TITLE
I have two flexsliders in sperate content editor on same page,Two sliders, one at the top (3 slides) and one at the bottom (5 slides). The controls are all showing only below the bottom slideshow, so the top one is showing no circles, and the bottom one is showing 3 + 5 circles. 

### ISSUE THREAD

**Issue by azamali** [woothemes/FlexSlider#1072]
I tried changing the ID but does not help $(window).load(function () {
          $('#news-flexslider').flexslider({
              controlsContainer: ".flexslider"
          });
      });
	</script><div class="flex-container" id="news-flexslider" style="min-height: inherit"><div class="flexslider" id="divSlider" style="min-height: inherit"><ul class="slides">

The direction nav adds up every time this runs. Please advice

**Comment by mattyza** [comment]
Hi @azamali.

It looks like you've declared two slideshows with the same JavaScript call.

You'd need to call `$( '#your-selector-name' ).flexslider();` for each separate slideshow. :)
