### ISSUE TITLE
How to use Laptop Slider?

### ISSUE THREAD

**Issue by TheZoker** [woothemes/FlexSlider#1087]
Hi there,

On a lot of pages you could see a Laptop slider made with FlexSlider, but I dont see a option to create it with this plugin...

How could I do so?

Thank you

**Comment by mattyza** [comment]
Hi @TheZoker.

I'm not entirely sure what you're referring to my "Laptop slider". A slider within a laptop screen image?

If so, this is a background image, placed behind your slideshow.

I hope this helps! :)
