### ISSUE TITLE
"Click" doesn't work!

### ISSUE THREAD

**Issue by koenpopma** [woothemes/FlexSlider#1097]
In many cases I use your FlexSlider-script. But currently (even) the click-events don't work... Panic! Greetings, Koen

Link to https://github.com/woothemes/FlexSlider/issues/1034. Issue is on the arrows and bullets. This only occurs in FireFox, it does work well in Safari.

**Comment by jeffikus** [comment]
Hi there

I've just tested in 2.3.0 and this is working, please reopen if you are experiencing something else.

Thanks,
