### ISSUE TITLE
Synced carousel skips first slide

### ISSUE THREAD

**Issue by clairefritz** [woothemes/FlexSlider#1140]
Hi there,

I am running into an issue that isn't new apparently: I have two synced flexsliders, one of which is the navigation for the other one.

My problem is when on the last thumbnail and clicking the "next" button, the carousel doesn't slide back to the first thumbnail. When clicking again it slides directly to the second thumbnail. In the meantime, the slider works.
I think the culprit is on line 655 in slider.flexAnimate(). If I remove "target !== 0" from the condition brackets, everything works as expected.

Can you please publish a fix for this?

Thanks,

Claire

**Comment by zanematthew** [comment]
This should be marked as duplicate of #946

**Comment by zanematthew** [comment]
@jeffikus I'm well aware, just left a comment for any others that come stumbling by.
