### ISSUE TITLE
Move the Carousel items one by one

### ISSUE THREAD

**Issue by SaranKS** [woothemes/FlexSlider#1144]
Hi ,

I am using thumbnail flex slider. I am using the following JQuery init code... But the carousel items slideshow not working properly. I need to fix the following issues.  Please help me. Send me the answer as soon as possible...

i)   In main slider one slide moves means, carousel item item also one slide will be moved
ii)  Both slider's slideshow should be in cycler loop

                jQuery(window).load(function() {
                jQuery('#carousel').flexslider({
                    animation: "slide",
                    controlNav: false,
                    animationLoop: true,
                    slideshow: true,
                    itemWidth: 240,
                    itemMargin: 5,
                    asNavFor: '#slider'
                });

                jQuery('#slider').flexslider({
                    animation: "slide",
                    controlNav: false,
                    animationLoop: true,
                    slideshow: true,
                    sync: "#carousel",
                    start: function(slider){
                        jQuery('body').removeClass('loading');
                    }
                });

            });

**Comment by Pankajdrync** [comment]
Is it working ?. I have same issue I need to carousel item move one by one but it move by 4 item.

**Comment by nag-abhishek** [comment]
is it resolve now I'm facing the same problem
