### ISSUE TITLE
Mousewheel problem

### ISSUE THREAD

**Issue by ibrahimaraci** [woothemes/FlexSlider#1150]
I want to use vertical slide and mousewheel true. I'm trying with touchpad and apple magic mouse when I scroll down with mousewheel slider going 3-4 slides next not next slide. How can I fix this?

**Comment by ivdekov** [comment]
@todesstoss Thank you for your solution above! `delta`, `deltaX`, and `deltaY` were undefined when I tried to console log them so I modified your code slightly to use the `wheel` event instead:

```
start: function(slider){
	//custom mousewheel:

	var timer = null;
	var wheeling = false;

	jQuery('.flexslider').on('wheel', function(event){
	  var deltaY = event.originalEvent.deltaY;

	  if(timer){
	    clearTimeout(timer);
	  }

	  if(!wheeling){
	    var target = deltaY < 0 ? slider.getTarget('next') : slider.getTarget('prev');
	    slider.flexAnimate(target, true);
	  }

	  wheeling = true;

	  timer = setTimeout(function(){
	    wheeling = false;
	  }, 60);

	});
}
```

It now works on Chrome, Firefox and Safari.

**Comment by agnieszkabugla** [comment]
@todesstoss Thanks for the solution! I just have one problem with it. SettingTimeout for 60 or 50 ms works perfect for a OS X touchpad or an apple magic mouse. When I use a different mouse, eg. logitech, 60 ms does not prevent the slider to go up or down few slides. I need to increase the timeout to 170 ms or so. But then the behaviour of the slider with magic mouse or touchpad isn't right. Any solutions for that?

**Comment by ibrahimaraci** [comment]
@agnieszkabugla this is working on all devices but it has other functions if you edit it for your purpose you can use it

`start: function(slider){
            var slider = jQuery('.post-slider').data('flexslider');
            var lastSlide = 0;
            slider.bind('mousewheel', function(event, delta, deltaX, deltaY) {
                event.preventDefault();
                event.stopPropagation();
                var getTimeNow = new Date().getTime();
                if(getTimeNow - lastSlide < 500 + 1000) {
                    event.preventDefault();
                    event.stopPropagation();
                    return;
                }

                if(delta < 0 ){
                    var goPos = slider.getTarget('next');
                }else{
                    var goPos = slider.getTarget('prev');            
                }

                var lasSlide = (slider.count)-1;
                var curSlide = slider.currentSlide;

                if(curSlide == 0){
                    if(delta < 0 ){
                        if(slider.count == 1){
                            jQuery('html, body').animate({'scrollTop': jQuery('.content').offset().top}, 1200);
                        }else{
                            slider.flexAnimate(goPos, slider.vars.pauseOnAction);
                        }
                    }else{
                        jQuery(".post-slider-wrapper").animate({
                            paddingTop: "75px"
                        }, 500, function() {
                            jQuery(".post-slider-wrapper").animate({paddingTop : "0px"}, 500)
                        });
                    }
                }else if(curSlide > 0 && curSlide < lasSlide){
                    slider.flexAnimate(goPos, slider.vars.pauseOnAction);
                }else{
                    if(delta > 0 ){
                        slider.flexAnimate(goPos, slider.vars.pauseOnAction);
                    }else{
                        jQuery('html, body').animate({'scrollTop': jQuery('.content').offset().top}, 1200);
                    }
                }
                lastSlide = getTimeNow;
            });
        }`

**Comment by agnieszkabugla** [comment]
Thanks @ibrahimaraci :) 
I modified it a little bit and ended up with this:
```js
            start: function(slider){
                //custom mousewheel:
            
                var slider = jQuery('.new-slider').data('flexslider');
                var lastSlide = 0;

                slider.on('wheel', function(event) {
                    var deltaY = event.originalEvent.deltaY;
                    var getTimeNow = new Date().getTime();

                    if(getTimeNow - lastSlide < 400 + 700) {
                        return false;
                    }                  
        
                    if(deltaY < 0 ){
                        var goPos = slider.getTarget('prev');
                    }else{
                        var goPos = slider.getTarget('next');            
                    }
                            
                    slider.flexAnimate(goPos, slider.vars.pauseOnAction);

                    lastSlide = getTimeNow;

                    return false;
                });
            }
```
