### ISSUE TITLE
Jquery.validate conflict

### ISSUE THREAD

**Issue by marcieee** [woothemes/FlexSlider#1154]
In my case Jquery.validate caused flex-control-nav to stop working, even though I have not found errors in the js console.
As soon as I removed the link to the script the slider started to tunction as normal.
Hope this can be useful to flexslider development.

**Comment by mattfletcher** [comment]
Any comment on the reasons for closing this?

**Comment by jeffikus** [comment]
@mattfletcher - please see http://develop.woothemes.com/flexslider/2015/03/18/flexslider-future-forecasting/
