### ISSUE TITLE
v.2.2.2 – resize doesn't work

### ISSUE THREAD

**Issue by koenpopma** [woothemes/FlexSlider#1159]
Hello, 

At this moment, when you zoom of resize, the flexslider doesn't resize: the slide-width is stuck somehow, even with css width: 100%.

Could you take a look at that?

Thanks,

Koen

PS: It works fine in v2.2.0, but in this version the arrows won't work (checked everything, also css to max z-index, but is has no effect) at https://github.com/woothemes/FlexSlider/issues/1034.

**Comment by jeffikus** [comment]
Hi there

I've just tested in 2.3.0 and this is working, please reopen if you are experiencing something else.

Thanks,
