### ISSUE TITLE
Flexslider stop animating switching to another browser tab

### ISSUE THREAD

**Issue by arshadabm** [woothemes/FlexSlider#1166]
When I switch the browser tab or open some other software and come back to that page Flexslider stop animating and freeze and it goes to the first slide. When I am on the page all things are going good I mean next and previous buttons are working fine and the slide is also animating as required.

    jQuery(document).ready(function() {
            jQuery("#flexslider-123").flexslider({
                animation: "slide",
                controlNav: false,
                directionNav: true,
                itemWidth: 200,
                itemMargin: 0,
                minItems: 1,
                maxItems: 2,
                move:1
            });
    });

All other things are going good as expected. Anyone can help please.

**Comment by daveschwerstein** [comment]
Why was this closed without a comment? This is happening for me as well. Upon debugging, it looks as if after switching tabs, slider.animating method is set to true before it slides. Of course, if it is set to true before the slider.animateSlides is called, the flexAnimate function will never be called and the slider becomes frozen.

**Comment by trlarson** [comment]
:+1:

**Comment by jeffikus** [comment]
@daveschwerstein please see http://develop.woothemes.com/flexslider/2015/03/18/flexslider-future-forecasting/

**Comment by daveschwerstein** [comment]
Thank you @jeffikus. We will try and transfer to 2.4.0 and check if the issue still exists.
