### ISSUE TITLE
Carousel - Number Of Items On Resize

### ISSUE THREAD

**Issue by nanakomeah** [woothemes/FlexSlider#1170]
Guys how do i archive something like this http://tenplay.com.au their carousel items EXACT...What am i doing wrong.

(function() {
 
  // store the slider in a local variable
  var $window = $(window),
      flexslider;
 
  // tiny helper function to add breakpoints
  function getGridSize() {
    var n = window.innerWidth;
            return n >= 0 && n <= 500 ? 1 : n >= 501 && n <= 800 ? 2 : n >= 801 && n <= 1e3 ? 3 : n >= 1001 && window.innerWidth <= 1600 ? 4 : 5;
  }
  
	r = function (n) {
		return n && t() < 2 ? 1 : n && t() > 2 ? 3 : t()
	}
	
  $(function() {
    SyntaxHighlighter.all();
  });
 
  $window.load(function() {
    $('.flexslider').flexslider({
    animation: "slide",
    animationLoop: false,
	slideshow: false,
	controlNav: false,
	slideshowSpeed: 900,
	animationSpeed: 900,
	initDelay: 0,	
	slideToStart: 0,
    itemWidth: 285,
    itemMargin: 30,
	minItems: getGridSize(), // use function to pull in initial value
	maxItems: getGridSize() // use function to pull in initial value
    });
  });
 
  // check grid size on resize event
  $window.resize(function() {
    var gridSize = getGridSize();
 
    flexslider.vars.minItems = gridSize;
    flexslider.vars.maxItems = gridSize;
  });
}());

**Comment by vlrprbttst** [comment]
same issue here: https://github.com/woothemes/FlexSlider/issues/1452
