### ISSUE TITLE
Bower Support

### ISSUE THREAD

**Issue by gjhead** [woothemes/FlexSlider#1171]
Would be great to have support for Bower again.

**Comment by hellopablo** [comment]
+1

**Comment by pribilinskiy** [comment]
667 issues! Woo!

**Comment by mishelen** [comment]
+1.

**Comment by martinbean** [comment]
+1

Any chance of getting a Bower manifest file added to this project so I can specify the version of Flexslider to include in my projects?

**Comment by jeffikus** [comment]
@martinbean i am working on this. No ETA at present.

**Comment by jeffikus** [comment]
I've just added support - see #843 and http://develop.woothemes.com/flexslider/2015/05/27/install-flexslider-using-bower-or-npm/ for more

**Comment by martinbean** [comment]
Awesome. Thanks, @jeffikus!
