### ISSUE TITLE
Fade + Different Height Elements + Smooth Height

### ISSUE THREAD

**Issue by wpexplorer** [woothemes/FlexSlider#1173]
Doesn't really work because the slides are simply given an opacity of 0 which means the flexslider height doesn't change but stays the height of the largest slide leaving a white space under the slider.

The older method of using display:none; worked much better for this.

**Comment by krishunt** [comment]
Why was this issue closed? The bug remains to this day.

**Comment by jeffikus** [comment]
@krishunt please provide either screen capture, screenshots, or a live url of the problem so I can test and debug.
