### ISSUE TITLE
Specifying GPL v2 only or GPL v2 and any later version

### ISSUE THREAD

**Issue by redndahead** [woothemes/FlexSlider#1176]
Currently the readme says that the license is GPL v2.  Could you help to clarify that it's either GPL v2 only or GPL v2 or any later version in the readme file? It makes a difference for projects like drupal that may distribute the library within certain downloads. We would prefer GPL v2 or any later version if we had a choice.

**Comment by jeffikus** [comment]
@mattyza can you shed some light on this?

**Comment by mattyza** [comment]
@jeffikus Lets adjust the readme to reflect GPL V2 and later.
