### ISSUE TITLE
Wordpress FlexSlider does not work on Chrome

### ISSUE THREAD

**Issue by d-ani-s** [woothemes/FlexSlider#1199]
The FlexSlider works strange  in Chrome. The slides are not visible until some point.
It works on Safari, FF and IE. I've made the following changes:
1. commented  -webkit-backface-visibility:  hidden; for .post-slider .slides > li
2. set  useCSS : false in the flexslider init script

**Comment by mattyza** [comment]
Hi @d-ani-s.

This sounds like your WordPress template is using an out of date version of FlexSlider.

Please upgrade to the latest version, available at http://github.com/woothemes/flexslider/releases/latest/.

Thanks. :)
