### ISSUE TITLE
Pause on hover : setting this property to false has no effect

### ISSUE THREAD

**Issue by dwainm** [woothemes/FlexSlider#1211]
When setting the pause on hover to false the slider still pauses on hover. I've only tested this in Chrome so far.

**Comment by jeffikus** [comment]
Hi guys

Will have this fixed for 2.5.0.

For my own reference:
#790 
#712 
#706

**Comment by jeffikus** [comment]
Tested in 2.5.0 - works, please reopen if you aren't satisfied.
