### ISSUE TITLE
Not working with jquery 1.11.1

### ISSUE THREAD

**Issue by vanso-waqar** [woothemes/FlexSlider#1221]
Hi I am using flexslider 2.2
For some reason its not working with jquery 1.11.1.
It runs perfectly with jquery 1.11.0
I can't downgrade the version since using a ruby gem.
Can you please tell me work around or a fix.

Thanks

**Comment by WolfHook** [comment]
@medvjed Thank you for pointing out the jQuery UI issue. I was ready to start punching holes in things till I found this.

**Comment by maybemaker** [comment]
:+1: thanks,
