### ISSUE TITLE
Uncaught TypeError/Uncaught ReferenceErro

### ISSUE THREAD

**Issue by troubletribbles** [woothemes/FlexSlider#1224]
I'm using FlexSlider 2.2.2 and he following snippet is generating two jQuery errors       
Uncaught TypeError: Cannot read property 'vars' of undefined 
Uncaught ReferenceError: SyntaxHighlighter is not defined 

    		jQuery(document).ready(function(){
    	
      // store the slider in a local variable
      var jQuerywindow = jQuery(window),
          flexslider;
     
      // tiny helper function to add breakpoints
      function getGridSize() {
        return (window.innerWidth < 600) ? 1 :
               (window.innerWidth < 900) ? 3 : 3;
      }
     
      jQuery(function() {
        SyntaxHighlighter.all();
      });
      
      jQuery('.flexslider').flexslider({
        animation: "slide",
        animationLoop: false,
        itemWidth: 290,
        itemMargin: 0,
    	prevText: " ",
    	nextText: " ",
     minItems: getGridSize(), // use function to pull in initial value
          maxItems: getGridSize() // use function to pull in initial value
        });
     // check grid size on resize event
      jQuery(window).resize(function() {
        var gridSize = getGridSize();
     
        flexslider.vars.minItems = gridSize;
        flexslider.vars.maxItems = gridSize;
      });
    });

**Comment by Ambient-Impact** [comment]
I don't know if you've already solved this, but the fixes are like so:

1) Remove
```javascript
jQuery(function() {
    SyntaxHighlighter.all();
  });
```
It's only used on the demo, and the error you're getting is because you don't have `SyntaxHighlighter`.

2) There's a known issue with the demo where it's missing this
```javascript
			start:		function(slider){
				flexslider = slider;
			}
```
It should be placed in the .flexslider() call, e.g. after `maxItems: getGridSize()`

**Comment by ajithfort** [comment]
thanks it worked
