### ISSUE TITLE
FlexSlider disappears in Blogger

### ISSUE THREAD

**Issue by willylo** [woothemes/FlexSlider#1233]
Dear Friends,

i'm a total newbie on web design, recently i downloaded a free template for my blog (Google Blogger).
it has Flexslider inside the xml file.

it works perfectly on Chrome both PC & Android for several weeks until today,
the slideshow disappears..

i tried to remember what was the last modification i put on the blog, and couldn't find any.
The only modification i did was changing some texts, and the URL location of the slideshow images.
The original template came up with 4 images, i changed them several weeks before, using my own images with same width & height like the original ones.
and it works fine until today.

After disappeared, i did re-upload the .xml using Restore Template menu, but still the slideshow is missing.
so, i decided to remove the blog completely, and Create a New Blog, then upload the .xml template again.
It works at first, but after several refresh, disappeared again.
i have deleted my blog three times :(

Please help me, any solution or tips will be appreciated.
Thank you very much before.

Regards,
Willy

**Comment by mattyza** [comment]
Hi @willylo,

This sounds like a bug in the blog template you're using.

I'd suggest contacting the template author for further debugging.

Thanks so much. :)
