### ISSUE TITLE
When animation is "fade" (or unset), controlNav links disappear

### ISSUE THREAD

**Issue by robertsimpson** [woothemes/FlexSlider#1236]
Hi folks,

When loaded without any parameters the controlNav links don't appear on the carousel, but when set to "slide", they do.

Any ideas?

Cheers,
Robert

**Comment by robertsimpson** [comment]
Has this issue been resolved?

**Comment by jeffikus** [comment]
@robertsimpson this is an extremely old issue. Please test with the latest version and let me know if the issue persists.
