### ISSUE TITLE
how can i create video slider with thumbnail like my screenshot 

### ISSUE THREAD

**Issue by ahmed3eraqi** [woothemes/FlexSlider#1241]
![image](https://cloud.githubusercontent.com/assets/9159804/5341106/3a5e1fb8-7ea8-11e4-9c67-1603bc979c83.png)

**Comment by jeffikus** [comment]
Hi there

You would use this example -> http://flexslider.woothemes.com/thumbnail-controlnav.html where this code:
```html
<li data-thumb="slide1-thumb.jpg">
      <img src="slide1.jpg" />
    </li>
```
Would become:
```html
<li data-thumb="slide1-thumb.jpg">
      // Video Embed goes here
    </li>
```
You would do that for each slide. Hope that makes sense!
