### ISSUE TITLE
Enable multiple sliders by adding post id (on a single page)

### ISSUE THREAD

**Issue by marypo** [woothemes/FlexSlider#1256]
Hello,
I'd like to enable multiple sliders on a single page. 

Each slider is part of a post with a dynamically assigned id i. e. **id="slider-{entry_id}"** . 
I thought I might use this id to enable all sliders on my page by calling it in the script. 
At the moment, my script looks like this:
```
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('#slider').flexslider({
        directionNav: false,
        smoothHeight: true
    });
  });
</script>
```
**Problem: Where/How can I add the id in this?** I'm still quite new to JS and have been trying for two days now, reading on jquery and trying bits of code but nothing worked. So any help would be highly appreciated!

**Comment by rajeshaspl** [comment]
Hi marypo,

If you are using drupal views you can assign id to Flexslider.

In drupal view select "Format" as a "Flexslider"
In settings you can get the "Element Id" Label , here you can add the Id for flexslider.

**Comment by marypo** [comment]
Hi rajeshaspl,

Thanks for your reply! I'm not using Drupal, I'm working with ExpressionEngine. Being with Drupal, could you tell me what the script looks like in there? Maybe this would help …

**Comment by marypo** [comment]
Nobody out there who can help? I won't beat you for advice ;-)

**Comment by jeffikus** [comment]
Hi there

You could change the javascript in your case on the third line to either be specific by id like this:
$('#slider-12').flexslider({
In that case the slider ID is 12.
OR
What you could do is add a class to each slider html and then do this: https://gist.github.com/jeffikus/ac62f41aecfdadf362b4

Reopen if you don't get it to work :)
