### ISSUE TITLE
Duplicated first image on animation 'slide'

### ISSUE THREAD

**Issue by miloche1701** [woothemes/FlexSlider#1259]
I have pretty much the same issue as #975, but in my case, removing the line :
 <code>slider.container.append(slider.slides.first().clone().addClass('clone').attr('aria-hidden', 'true')).prepend(slider.slides.last().clone().addClass('clone').attr('aria-hidden', 'true'));</code>
didn't help.
I'm using JQuery 1.11.1, maybe there is a conflict between flexslider and this version?

**Comment by Spongsta** [comment]
@miloche1701, I'm also using jQuery 1.11.1.  I replicated your issue but then realized I was including the jquery.flexslider-min.js file and had edited the jquery.flexslider.js file.  I just updated my include to point to the edited file and the issue was corrected.

**Comment by jeffikus** [comment]
Tested with 2.5.0, jQuery 1.11.1 and cannot replicate. Marking as resolved.
