### ISSUE TITLE
Pause Main Slide on Thumbnail Swipe when viewing on iPad - Flexslider 2.2.2

### ISSUE THREAD

**Issue by Basher72** [woothemes/FlexSlider#1262]
I am new to this and not a coder so if you can help please explain in an simple terms as possible. I currently have V2.0 of the flex slider on my web site with a gallery that has around 25 thumbnails. When viewing this on an iPad if you swipe across the thumbnails the main slide above pauses and doesn't do anything until you click on the image in the thumbnails.

I have an issue with windows 8 and google chrome which seems to have been fixed in the new version (2,2.2) so I would like to use this.

In the new version 2.2.2 when I do the same thing, so swipe across the thumbnails the main slide jumps as you swipe across every 4 or 5 image which I find very annoying. How do I turn this off so it works like the old version where it just paused until you selected an image?

Hope someone can help.

**Comment by jeffikus** [comment]
Hi there

Afaik this should be resolved in 2.5.0 - please reopen the issue if the problem persists.
