### ISSUE TITLE
Flexslider carousel when scroll to end, it show more white background

### ISSUE THREAD

**Issue by vneverz** [woothemes/FlexSlider#1264]
can it show the first img not white space?
see this -> http://greenripple.mynet.com.tw/product_detail.php?id=20 
![26115533](https://cloud.githubusercontent.com/assets/5225912/5895175/49b5047e-a552-11e4-8cc8-e4b71cb90bce.jpg)

**Comment by jeffikus** [comment]
Hi there, there is a page redirect on this. Please reopen once the redirect has been sorted out.
