### ISSUE TITLE
Slides on when not visible on modern browsers

### ISSUE THREAD

**Issue by dahmian** [woothemes/FlexSlider#1266]
It looks like there is a bug on pauseInvisible for browsers that support PageVisibility without vendor prefixes.

#### Steps to reproduce
* go to a page with a slider on the latest Chrome
* note how long it takes for the slider to advance
* wait until a slide has advanced
* note the slide you are currently on
* open a new tab to goolge.com and wait enough time for the slider to advance
* go back to the slider tab
* note how the slide immediately advances
* try the same on Firefox
* note how firefox does not advance immediately, instead it seems to advance while you are on another tab

#### Expected behavior
Once returning to the slider from another tab, the slider should still be on the same slide.

#### Analysis
There looks like there is code to stop advancement in FlexSlider, but on modern browsers it's not working because of a bug. See https://github.com/dahmian/FlexSlider/commit/88810858498be3b5813d433846bb09dc10647b7d.

Tested on OS X 10.10.2 (14C109) with Chrome 40.0.2214.94 (64-bit)

https://www.youtube.com/watch?v=q7G8uv_9dsI

**Comment by jeffikus** [comment]
Will test for the 2.3.0 cycle

**Comment by jeffikus** [comment]
I noticed that the slide immediately changes when I change back to that tab, I don't however experience the same behavior as you do - can you specify OS and the build number of your chrome please? If possible can you provide me with a short screencast video of how you experience it?

**Comment by dahmian** [comment]
I believe we are experiencing the same behavior, I just incorrectly wrote my bug description. Sorry about that. Yes, once I go bad a tab, the slide immediately changes.

Here is a video of the issue: https://www.youtube.com/watch?v=q7G8uv_9dsI

**Comment by jeffikus** [comment]
Ok, I see what you mean now - I'll have to do some further debugging on this one. I'll check in other browsers too, something may have changed on the Chrome side of things.

**Comment by jeffikus** [comment]
I've found the root cause for this. It's a scoping issue - I'm reworking the code today.
