### ISSUE TITLE
I need ios swipe restriction on horizental

### ISSUE THREAD

**Issue by mask2012** [woothemes/FlexSlider#1268]
it occurs only on ios in my test , if we swipe from left top to right bottom, ios will take it as a horizental swipe, and I don't need this ,  anyone gives me an solution?  thanks a lot!!

**Comment by jeffikus** [comment]
Hi there, can you provide a url to test this on please?

**Comment by aghouseh** [comment]
Running into this as well. Maybe either a swipe sensitivity setting or a way to detect opposite axis swipe and block slide traversal until the touchend event?

**Comment by jeffikus** [comment]
Thanks guys, I'd like to look into this for you, can you provide live URLs so I can see what you are seeing? @aghouseh @mask2012

**Comment by mask2012** [comment]
http://mask2012.sinaapp.com/flexslider-bug/guide.html
I'm chinese and hope you can visit it, this problem seems only happen on iphone, when I swipe left,right,up,down, it's working good, but if swipe frome left bottom to right top, it's not working on my purpose.

**Comment by jeffikus** [comment]
Ok I kind of see what you mean - I found where this is controlled in the code and am looking into a fix, I might even bump today's release so I can try get it out tomorrow! :)

**Comment by jeffikus** [comment]
Ok so I took a further look into this, and I definitely dont think this will be in this release or the next. It's a grey area as to the UX of how the user interacts with the touchscreen. I'm going to tag this for 2.5.0 so that further research can be done.

**Comment by mask2012** [comment]
thanks a lot jeffikus!!

**Comment by jeffikus** [comment]
Ok, there is much to be done here unfortunately - unless you write custom code to catch this. I've tested quite a lot on this and the best case here is to write a custom handler for your use case. The majority of people will not require this and I don't feel it warrants a change/addition of logic to the core, because it isn't a bug imo.
