### ISSUE TITLE
Drupal Status Report shows Flex Slider - Incorrect Version Detected

### ISSUE THREAD

**Issue by lalit774** [woothemes/FlexSlider#1271]
Hey,

In drupal flexslider module check version from js file. Its broken because jquery.flexslider.js has comment with version number as following.
/*
 * jQuery FlexSlider v2.3.0
 * Copyright 2012 WooThemes
 * Contributing Author: Tyler Smith
 */

https://www.drupal.org/node/1700100
https://www.drupal.org/node/2305609

But jquery.flexslider-min.js doesnot contain any comment. so drupal is unable to read version for js file.

Could you please add following comment in jquery.flexslider-min.js file on top. So drupal can access version.

/*
 * jQuery FlexSlider v2.3.0
 */

**Comment by chrisgross** [comment]
I second this. This is a critical bug.

**Comment by bradallenfisher** [comment]
Is this something you would be willing to do? I know that this project is in no way drupal specific but could really help out the community. Thanks!

**Comment by lalit774** [comment]
Hi,

I don't have access to commit in repo. could anyone apply attached patch to
master branch and close the issue..

On Tue, Feb 17, 2015 at 4:53 PM, bradallenfisher <notifications@github.com>
wrote:

> Is this something you would be willing to do? I know that this project is
> in no way drupal specific but could really help out the community. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/FlexSlider/issues/1271#issuecomment-74762238>
> .
>



-- 
Thanks & Regards

Lalit

**Comment by jeffikus** [comment]
Duplicate bug - I've already assigned this in #1275
