### ISSUE TITLE
LESS - font path variable

### ISSUE THREAD

**Issue by Ninos** [woothemes/FlexSlider#1274]
Hey there,
it should be possible to define a font path variable in the less file. If you want I can add a pr, but it should very easy to add something like
```
@font-path: "../fonts";
@font-face {
  font-family: 'flexslider-icon';
  src:url('@{font-path}/flexslider-icon.eot');
  src:url('@{font-path}/flexslider-icon.eot?#iefix') format('embedded-opentype'),
    url('@{font-path}/flexslider-icon.woff') format('woff'),
    url('@{font-path}/flexslider-icon.ttf') format('truetype'),
    url('@{font-path}/flexslider-icon.svg#flexslider-icon') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by jeffikus** [comment]
PR are always welcome :) try get it in before 23 Feb so I can get it into 2.4.0 - I'm assigning to 2.4.0 for now, but will bump to 2.5.0 if I dont see a PR for this.

**Comment by jeffikus** [comment]
Added your changes into release branch! thanks!
