### ISSUE TITLE
Version information removed in jquery.flexslider-min.js

### ISSUE THREAD

**Issue by rpsu** [woothemes/FlexSlider#1275]
Version information removed in jquery.flexslider-min.js and this breaks at least Drupal module version checking. How about re-include header in minified js-file?

**Comment by rpsu** [comment]
See https://www.drupal.org/node/2428541

**Comment by jeffikus** [comment]
Thanks, was not aware of how Drupal does this, will fixed in the next release scheduled for 23 Feb

**Comment by rpsu** [comment]
Thanks! 

And to be precise; it is not Drupal that does it this way but a contributed Flexslider -module which glues Flexslider and Drupal together.

**Comment by jeffikus** [comment]
Ah thanks for clarifying!

**Comment by dw72** [comment]
It is possible to merge this fix to master branch?

**Comment by jeffikus** [comment]
@dw72 it is scheduled to be merged.

**Comment by lalit774** [comment]
Hi

could you please patch same issue into flexslider release-2-3-0 branch. Because lot of people use flexslider 2.3.0 also.

**Comment by jeffikus** [comment]
Hi there, no, we wont be patching the 2-3-0 branch as it has been removed. Branches once merged with master are removed. We do not maintain older releases, we maintain the current release which you can always check using this link -> https://github.com/woothemes/flexslider/releases/latest
