### ISSUE TITLE
no slide pause when html5 video plays

### ISSUE THREAD

**Issue by telemarker** [woothemes/FlexSlider#1286]
hi, i sucessfully added selfhosted clips via the html5 video tag to the slider.
1. how can i make flexslider stop doing the slideshow if the video is playing?
2. how can i play the slideshow when the video is paused?
3. how can i resume the slideshow when the video ends?
4. how can i a rewind the video when the next slide is shown?
thanks

**Comment by telemarker** [comment]
okay google does not give an anwser on this one, so i had to solve it by myself.

the example uses a slider with 2 images and 2 videos.
< image1 / video 1 / image 2 / video 2 >
please note that the div id is not flexslider but slider.

```
<div id="slider" class="flexslider">
         <ul class="slides">
                    <li><img src="/image1.png" /></li>
                    <li><video onplay=pauseslider() onpause=playslider() onended=resumeslider() controls preload="none" width="100%" height="100%" poster="/video1.jpg" >
                        <source src="/video1.mp4" type='video/mp4' />
                        <source src="/video1.webm" type='video/webm' />   
                    </video></li>
                    <li><img src="/image2.jpg" /></li>
                    <li><video onplay=pauseslider() onpause=playslider() onended=resumeslider() controls preload="none" width="100%" height="100%" poster="/video2.jpg" >
                        <source src="/video2.mp4" type='video/mp4' />
                        <source src="/video2.webm" type='video/webm' />   
                    </video></li>
        </ul>
    </div>
```

**Comment by c9dd** [comment]
This has helped loads. Thanks

**Comment by jeffikus** [comment]
Hi guys, can you please test this again with the 2.5.0 release and let me know if the issue persists. Reopen if it does.

**Comment by marietaGonzales** [comment]
thanks!! i was searching the solution of this! THANKS!

**Comment by al-ramadhan** [comment]
What if we used iframe instead <video> tag? Please help

**Comment by marietaGonzales** [comment]
i used another solution 
this is the slider with videos 
               <?php $url_actual = "http%3A%2F%2F" . $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
											$url_actual_video=str_replace("/", "%2F", $url_actual);?>
                    <div id="video-slider" class="row">
					<div>
							<div class="video container">
								<div class="col-2-3 image-video">
									<img id="first" class="openvideo" src="img/aprendimos.jpg" data-video="video/Aprendimos_V2" data-url="<?php echo $url_actual_video;?>" data-slider="SI"/>
									<div id="first-video"></div>
								</div>
								<div class="col-1-3 text-video">
									<h3><a href="#">En  aprendimos</a></h3>
								</div>
							</div>
							<div class="video container">
								<div class="col-2-3 image-video">
									<img id="second" class="openvideo" src="img/dakar.jpg" data-video="video/_Dakar_02" data-url="<?php echo $url_actual_video;?>" data-slider="SI"/>
									<div id="second-video"></div>
								</div>
								<div class="col-1-3 text-video">
									<h3><a href="#">text</a></h3>
								</div>
							</div>
						</div>
						<div class="slider-nav dark">
                                <ul>
                                    <li><a href="#" class="prev"></a></li>
                                    <li><a href="#" class="next"></a></li>
                                </ul>
                            </div>

Then My slider.js 

      jQuery('#video-slider').flexslider({
        animation: "fade",
        selector : "div > .container",
        customDirectionNav: $("#video-slider .slider-nav ul li a"),
        controlNav:false,
        animationSpeed: 1500,
        slideshowSpeed: 4000,
        animationLoop: true
		});
         function pauseslider() { $('#video-slider').flexslider("pause"); }
         function playslider() { $('#video-slider').flexslider("play"); }
        function resumeslider() { $('#video-slider').flexslider("next"); $('#video-slider').flexslider("play");}

This is my video.js 

    jQuery(document).ready(function() {
       jQuery('.openvideo').bind('click', function(e) {
			var is_slider = jQuery(this).attr('data-slider');
			var controles_slider=" ";
			if (is_slider =="SI"){
				pauseslider();
				var controles_slider ="onplay=pauseslider() onpause=playslider()";
			}
			var video_dir = jQuery(this).attr('data-video');
			jQuery(this).css('display','none');
			var actual_id =jQuery(this).attr('id');
			var video_div_id= "#"+actual_id+"-video";
			var video_id =actual_id+"-video-id";
			var url= jQuery(this).attr('data-url');
			var url= url.replace("index.php","");
			var port = location.port;
			console.log(port);
			if(port !="80"){
				console.log("diferente");
				var url = url.replace("ypfb.web", "ypfb.web:"+port);
			}
			console.log(url);
			
			//var url ="http%3A%2F%2Fypfb.web:88%2F";
			var video_dir2=video_dir.replace("/", "%2F");
			var video_ie_dir= url+video_dir2;
			console.log(video_ie_dir);
			//console.log(video_ie_dir);
			var video_img = jQuery(this).attr('src');
			var video_img_ie = video_img.replace("/", "%2F");
			//console.log(video_img);
			if(BrowserDetect.browser == 'Explorer' && (BrowserDetect.version == 8 || BrowserDetect.version == 7)){
			//if(BrowserDetect.browser == 'Explorer'){
				console.log("Es Explorer a continuacion el object");
				console.log('<object type="application/x-shockwave-flash" data="http://flashfox.googlecode.com/svn/trunk/flashfox.swf" width="416" height="276">'+
					'<param name="movie" value="http://flashfox.googlecode.com/svn/trunk/flashfox.swf" />'+
					'<param name="allowFullScreen" value="true" />'+
					'<param name="wmode" value="transparent" />'+
					'<param name="autostart" value="true" />'+
					'<param name="flashVars" value="autostart=true&amp;controls=true&amp;poster='+url+video_img_ie+'&amp;src='+video_ie_dir+'.mp4&amp;autoplay=true" />'+
					'<img alt="YPFB Video" src="'+video_img+'" width="416" height="276" title="No video playback capabilities, please download the video below" />'+
					'<a href="https://get.adobe.com/flashplayer/?loc=es">Upload flash </a>'+
					'</object>');
				$(video_div_id).append('<object type="application/x-shockwave-flash" data="http://flashfox.googlecode.com/svn/trunk/flashfox.swf" width="416" height="276">'+
					'<param name="movie" value="http://flashfox.googlecode.com/svn/trunk/flashfox.swf" />'+
					'<param name="allowFullScreen" value="true" />'+
					'<param name="wmode" value="transparent" />'+
					'<param name="autostart" value="true" />'+
					'<param name="flashVars" value="autostart=true&amp;controls=true&amp;poster='+url+video_img_ie+'&amp;src='+video_ie_dir+'.mp4&amp;autoplay=true" />'+
					'<img alt="YPFB Video" src="'+video_img+'" width="416" height="276" title="No video playback capabilities, please download the video below" />'+
					'</object>');
			}
			else{
				
				$(video_div_id).append('<video id ="'+video_id+'" controls poster="'+video_img+'" width="90%" height="276" autoplay="autoplay"'+controles_slider+' >' + 
				'<source src="'+video_dir+'.mp4" type="video/mp4" />'+
				'<source src="'+video_dir+'.webm" type="video/webm" />'+
				'<source src="'+video_dir+'.ogv" type="video/ogg" />'+
				'</video>');
			}
	 });


});

**Comment by telemarker** [comment]
thanks guys, its good to see that this also helps others!
@marietaGonzales that looks very complicated but surely does more than dealing with html5 videos.

**Comment by marietaGonzales** [comment]
yes This works for ie8, ie9 , ie10 , ie11  and Chrome And Firefox
