### ISSUE TITLE
Flexslider carousel images overlapping; adding an ngClick event to the .flex-prev and .flex-next arrows

### ISSUE THREAD

**Issue by amirtcheva** [woothemes/FlexSlider#1288]
I'm having an issue with Flexslider where some of the images over lap in later sets of images (after the first set) hitting the right arrow makes some of the images go one on top of each other. Resizing the browser fixes this issue. 

I want to add an on click, or ngClick (in angular) event for the .flex-prev and .flex-next arrows in the carousel after they're been clicked to call a browser re-size event. How is this done in angular? 

Also, if anyone else is seeing this, is there a different way of fixing this issue? Re-sizing the browser is the only solution I'm able to find at this point.

**Comment by jeffikus** [comment]
Hi there

I've honestly never used FlexSlider in conjuction with Angular, however, it is on my todo list to try - I hope to be able to do that within a week. So I can give feedback by next week Friday.

However, what you could do is either target the element in jQuery using the .click() event or you could use the 'after' callback when you setup FlexSlider - check out this page http://www.woothemes.com/flexslider/ for the docs. 

Let me know if you get stuck setting that up!

**Comment by amirtcheva** [comment]
Thanks for the email! I actually did try just putting a click event on the
element, but it didn't do anything, not sure why. Let me know if you
discover something different! Thanks :)

-Alex

**Comment by jeffikus** [comment]
There is a trick you can do to hijack the click event completely, you can use preventDefault http://api.jquery.com/event.preventdefault/ but then the slider wont slide ;) I'll work on something for you for next week Friday!

**Comment by amirtcheva** [comment]
Oh wow! Thanks so much Jeff! :)

**Comment by jeffikus** [comment]
@amirtcheva I don't have anything on this at the moment unfortunately. I did do some further research on this and I'm not sure yet as to whether or not I'm going to add an Angular directive at this stage, reason being is that Angular 2 is starting to pickup traction and I need to learn it to compare how things have changed. I'm not closing this, but I am bumping it out of this milestone for now.

**Comment by jeffikus** [comment]
Hi @amirtcheva have you tried this repository? https://github.com/thenikso/angular-flexslider

**Comment by amirtcheva** [comment]
Hi Jeff, haven't seen it before. In the time I first posted a question, my team decided to go with an entirely different slider, haha. Thanks so much for your help, it's very much appreciated! :)

**Comment by jeffikus** [comment]
@amirtcheva ah sad to hear that but glad you found a solution :) Angular is definitely on my agenda, hopefully in the future! Out of curiosity which one did you go with?

**Comment by amirtcheva** [comment]
It's called OWL carousel, wouldn't say it's a better solution since we're already seeing some issues with the navigation on mobile >_< Thanks so much for being so responsive!

**Comment by jeffikus** [comment]
Cool, thanks for the info :) I have seen that one! Anytime :)

**Comment by Lawless55** [comment]
Hi @jeffikus & @amirtcheva, 

it would be hard to say what could be causing the issue without seeing any code. But my suspicion is that your instantiating Flex Slider after Angular's completes a digest. When the browser re-sizes it essentially 're-initializes' Flex Slider and rebuilds it, Jeff would know more about this, that is why it suddenly works after re-sizing the browser. The 'Angular' way around this is to tell the directive to apply the DOM changes to the scope by (one way) wrap it in a $timeout function.

However, if your still wanting to bind an ngClick, you could use a Flex Slider option called 'customDirectionNav' and assign an element to it `customDirectionNav : $('.custom-navigation a')` and then manually add the controls nav to your HTML markup. 

I have created a working Plunkr demonstrating this - http://plnkr.co/edit/ZPc38rWit53EcuHrSc8e?p=preview
