### ISSUE TITLE
IE slide animation image rendering

### ISSUE THREAD

**Issue by vtsource** [woothemes/FlexSlider#1289]
May have jumped the gun in closing issue and deleting all I typed. Also not sure how to recover deleted comment so I'll describe it again.
In IE9+, when slide is immediately "slid" a few slides forward or backward (with nav controls, keyboard controls or scripting) after window load, there is a slight delay in rendering of large slide images during the animation when they have not yet been cached causing the background of the parent element to be seen in place of the image during the animation for a brief moment until the image renders.
Only happens in IE9+ (tested and evident in IE11 as well).
Not evident in IE8 nor other tested browsers (Chrome/Firefox/Safari). In them, the slide animation image rendering is consistent.
*updated*
Managed to isolate the issue further and found a little workaround.
I have a setup where i load flexslider on document ready and pause it at start. Throughout this time I have a preloader going covering the screen while the images load. On window load I have the preloader fade out and start the flexslider.
In IE9, the slide animation image rendering issue is fixed with some conditional [if gt ie8] manual javascript image preloading, whereas in IE11(and 10 in IE11 emulation mode), for which I rely on a (conditional as well) callback to a javascript image preload function and done method before the preloader disappears (due to no support for window load in ie11), the rendering is only fixed by cycling through each slide manually with js prior to the initialization of the callback.
Used code from here http://www.javascriptkit.com/javatutors/preloadimagesplus.shtml to preload images.

**Comment by vtsource** [comment]
Upon further testing and trying to recreate the issue with flexslider demo code I've determined it's something in my code. Sorry to concern anyone.

**Comment by jeffikus** [comment]
Closing this, i will give this further consideration in the 3.0 cycle.

**Comment by vtsource** [comment]
No problem.
