### ISSUE TITLE
doesn't show slider in mobile!

### ISSUE THREAD

**Issue by h-rafiee** [woothemes/FlexSlider#1292]
Hello we use flexslider in our project and it have a bug ...
**Not showing images on slider in mobile device**
our code like that ...
```
<div id="slider" class="flexslider">
	  <ul class="slides">
		<li>
                        <img src="img/1.jpg" />
		</li>
	  </ul>
</div>
<script>
		$(document).ready(function() {
		  $('.flexslider').flexslider({
		    animation: "fade",
		    directionNav: false,
		    controlNav: false
		  });
		});
</script>
```
check this [link to Vip7!](http://vip7.ir)

**Comment by jeffikus** [comment]
Hi there

I've tested on iPhone 6 and seems to be working fine - please reopen with a screencast of the issue you are experiencing.

Thanks,
