### ISSUE TITLE
How to change output position of controlnav

### ISSUE THREAD

**Issue by Caspert** [woothemes/FlexSlider#1299]
I was wondering how I can change the output markup of Flexslider. What the problem now is, when I use thumbnails for controlNav, my directionNav `prev` and `next` will position at the bottom of all the thumbnail images.

What I want is that the directionNav markup will output directly after the `slider` div. Is this possible?

Casper

**Comment by jeffikus** [comment]
Hi Casper

Have you seen this example here -> http://wooslider.wordpress.dev/flexslider/demo/basic-slider-with-custom-direction-nav.html if that isn't what you are looking for please reopen the issue.

Thanks,
