### ISSUE TITLE
WTF are you doing?!

### ISSUE THREAD

**Issue by pribilinskiy** [woothemes/FlexSlider#1305]
There were about 600 issues and 80 pull requests then in an hour they all gone
Did you use some GitHub API to close those?
Is there a reason why those unresolved issues were closed?
Main question: what is the support plan?

http://i.imgur.com/N2yXNbe.png

**Comment by syntax53** [comment]
Maybe you should read the announcement: http://develop.woothemes.com/flexslider/2015/03/18/flexslider-future-forecasting/

**Comment by jeffikus** [comment]
Hi @pribilinskiy 

Thanks @syntax53 for linking to the post - we planned this in advance as most of those issues are no longer relevant, I've kept open the ones that are, as well as the pull requests. The reasoning is detailed quite extensively in the announcement post.

Thanks!
