### ISSUE TITLE
load picture when click arrow.

### ISSUE THREAD

**Issue by jinleileiking** [woothemes/FlexSlider#1310]
It will load all the picture at the moment .

I want to load one picture when click the arrow.

It is can be done ?

**Comment by jeffikus** [comment]
Hi there

I'm not sure what you mean here, can you provide me with an example?

**Comment by jinleileiking** [comment]
By default, This plugin will load all the images when page is opened.
I want it open one slide when it open. When click the right arrow, It send ajax to get the next slide picture.
Can it be done?

**Comment by jeffikus** [comment]
Hi there

In theory yes it is possible, we've covered this in issue #63
