### ISSUE TITLE
AutoPlay stop working (FlexSlider 2.4)

### ISSUE THREAD

**Issue by Air-Sidney** [woothemes/FlexSlider#1313]
FlexSlider 2.4. 
I reproduce 2 sutuation when slider stop and autoplay stop working with "slideshow: true and pauseOnAction: false". 
1) Video or Images content. Autoplay stop when we click on bullet.
2) Mixed content (Video and images) and "pauseOnHover: true".  If we click play video in some slide, slider stop sliding, after we click to pause video and slider begin sliding. But if we doing mouseover, autoplay stopped and not working.

**Comment by jeffikus** [comment]
Hi there

Afaik this was fixed in 2.5.0 release. See issue #1211 for further details.
