### ISSUE TITLE
smoothHeight and flex-viewport 0 height bug

### ISSUE THREAD

**Issue by BenRacicot** [woothemes/FlexSlider#1320]
Hello, I've been trying to track the cause of my flex-viewport height loading at 0px. It seems that several people around the net have had the same issue. 

Temporary solution:
I've added a min-height:200px; to try'n display the first image regardless of its actual height, then upon user prev/next navigation Flexslider's height calculation takes over. However it would be nice to fix this in order to have proper first image height when using smoothHeight.

Also, I am seeing 1px of the next flexslider `<li>`. Can't seem to hide it. Perhaps others have fixed this issue as well? Thanks in advance.

**Comment by micred** [comment]
Hi, as a workaround we add at page load something like this (it triggers a fake window resize):
```
function flexsliderHeightBugWorkaround() {
    // https://github.com/woothemes/FlexSlider/issues/1320
    $('.flexslider.container').each( function() {
        if ($(this).height() < 60) {
            $(window).resize();
            return false;
        }
    })
}

$(document).ready(function() {
    setTimeout(flexsliderHeightBugWorkaround, 500);
    setTimeout(flexsliderHeightBugWorkaround, 2000);
    setTimeout(flexsliderHeightBugWorkaround, 5000);
});
```

**Comment by greatghoul** [comment]
init flexslider in window.onload may help.

```
$(window).load ->
  $('.flexslider').flexslider
    directionNav: false
    smoothHeight: true
    slideshowSpeed: 3000
```

**Comment by feliperaul** [comment]
Same issue here.

Everytime it loads with smoothHeight, it loads at 0px

Can't wait for window.onload to load flexslider
