### ISSUE TITLE
Add LICENSE file to project root.

### ISSUE THREAD

**Issue by lsoendergaard** [woothemes/FlexSlider#1321]
It took me a while to figure out what license FlexSlider is actually using (only after googling I realized it's mentioned kinda casually in the readme). So I'd recommend to add a `LICENSE` file, containing the full license (gplv2 afaik), to the project root, to make the used license more obvious.

Thanks

**Comment by plutext** [comment]
Implications of using GPL-licensed client-side JavaScript: [http://greendrake.info/#nfy0]

Not sure whether that is intended?
