### ISSUE TITLE
PausePlay button issue

### ISSUE THREAD

**Issue by rpennacchio** [woothemes/FlexSlider#1323]
Hi guys,

There is an error with the Play/Pause button selector, in the current stylesheet, at line 193 :
".flex-pauseplay a .flex-play:before"
It should be :
".flex-pauseplay a.flex-play:before"

In the "theme.less" file, at line 203, "&" is missing.

:)

**Comment by jeffikus** [comment]
Hi there

Thanks for reporting :) I fixed this in the 2.5.0 release :) See #1293 for further details.
