### ISSUE TITLE
Bootstrap modal and Flexslide (Flexslide inside a modal)

### ISSUE THREAD

**Issue by penny19** [woothemes/FlexSlider#1327]
i put a flexslide inside a modal, when the modal is shown, the flexslide works incorrect. It seems all the contents are mixed together . 
the problem looks like martinbean met in the link: 
https://github.com/woothemes/FlexSlider/issues/182

but i don't know how to solve

**Comment by jeffikus** [comment]
Hi there

You need to initialize FlexSlider when you load the modal, in other words, on the click event or callback for the modal, you would call your .flexslider() method then. Not on window(load) or document(ready).

The reason for this is that if you don't, FlexSlider will think the height is zero.

Let me know if you get stuck! Thanks,

**Comment by stemie** [comment]
Hi Jeff,

I'm trying what you suggested but when the modal opens flexslider doesn't load (the images some times appears after I click in the modal but it's not working  properly). Any ideas where I'm going wrong?

    `$(".lodge-gallery-btn").click(function () {
            
            $(".bs-gallery-modal-lg").modal("show");

            $('#carousel').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: false,
                slideshow: false,
                itemWidth: 120,
                itemMargin: 5,
                asNavFor: '#slider'
              });
              $('#slider').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: false,
                slideshow: false,
                sync: "#carousel"
              });
        });`

**Comment by jeffikus** [comment]
Hi Stemie

I think you could try call the flexslider inside one of the modal callback events, see http://getbootstrap.com/javascript/#modals-events

Calling Flexslider straight after showing the modal most likely wont work now that I think about it a bit more.

**Comment by mangleshyadav** [comment]
In bs4 pass fliex slider code in modal callback function. And it work fine for me. 
 
$('#filmStripModal').on('shown.bs.modal', function () {

      $('#carousel').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        itemWidth: 210,
        itemMargin: 5,
        asNavFor: '#slider'
      });
      $('#slider').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        sync: "#carousel"
      });

    });
