### ISSUE TITLE
FlexSlider problem with jQuery hide

### ISSUE THREAD

**Issue by rodrigoruiz** [woothemes/FlexSlider#1330]
If I call hide() in a div that will contain the FlexSlider markup before calling flexslider(), it doesn't show the images.

How can I fix that?

**Comment by jeffikus** [comment]
Hi there

Why would you want to do that? FlexSlider will think that the height of the slider is zero, it has nothing to base the slider height on then.

**Comment by rodrigoruiz** [comment]
Exactly, that's why it should base it's height in a relative way, not with an absolute number.
I have 2 screens that use FlexSlider, I want to hide one of them and show another, and change that based on a menu click.

**Comment by jeffikus** [comment]
Sure, so then you would initialize FlexSlider on the click event when the image height can be calculated based on the DOM.

**Comment by rodrigoruiz** [comment]
The MenuController does not notify (nor does it want to) each of the separate controllers for each view, and the FlexSlider is initialized only once, when the views get loaded.
In order to do what you're saying, the MenuController would have to notify each separate specific controller and each controller would have to keep a pointer to all FlexSlider instances to reload it (or destroy and create a new one on every menu click).

**Comment by jeffikus** [comment]
You can just do a check for if the flexslider exists, if it doesnt, then load it, if not then continue as normal. You'd need to post a code example for me to assist, but that's the theory otherwise.
