### ISSUE TITLE
Problem image height

### ISSUE THREAD

**Issue by thecobe** [woothemes/FlexSlider#1339]
Hi all 
This slider is perfect as long as the width is greater than the height of the images but completely ruined when the image height is greater than the width
Any solutions?
I'm using the slider with thumbnail controlnav

**Comment by jeffikus** [comment]
Hi there

Sorry you are disappointed, but can you elaborate a little more please? Do you have a live url I can see what you mean on?

Thanks,

**Comment by thecobe** [comment]
Hi 
this is an example from your demo
http://www.bellimarco.com/demo/thumbnail-controlnav.html
I probably did not properly set up something
thanks for the support

**Comment by thecobe** [comment]
Hi 
any suggestion?

**Comment by sandrodz** [comment]
Yes I noticed this too, my workaround is to use smoothHeight set to true... I really don't like its animation, but fixes immediate problem.

**Comment by feliperaul** [comment]
Problem is that smoothHeight loads first slide with 0px for me ...

**Comment by thomasguillot** [comment]
I cannot replicate any of the issues above.

wontfix
