### ISSUE TITLE
ios 8.3 no slideshow with html5 video 

### ISSUE THREAD

**Issue by telemarker** [woothemes/FlexSlider#1342]
hi, i discovered that on ios 8.3. devices no slideshow appears if some li contains the html5 <video> tag with mp4 as source. please let me know soon how to fix this. can you fix it in flexslider, or has apple to do something?
regards
thomas

**Comment by jeffikus** [comment]
Hi Thomas

Do you have a live link I can test on my devices and in the iOS simulator please?

Thanks,

**Comment by telemarker** [comment]
yes, of course:
http://framegrabber-medien.com/projekte/
you can click on any project that contains video.
i checked it with this link:
http://framegrabber-medien.com/portfolios/schwedenspeicher/

its using webm and mp4 as video source.

**Comment by jeffikus** [comment]
Hi there

The slider is definitely there, I inspected the source, however, the height is set to 0px, do you have any custom css for the responsiveness of the site that could be interferring?

**Comment by telemarker** [comment]
hey jeffrey,
yes there are several css files. if you tell me the element that has height: 0px; i will check if i can change that.
in my tests the sliders appears on an iphone 5 with ios 8.3 when there's no video included.
http://framegrabber-medien.com/portfolios/nivea-haus/ works quite well (but only with pictures).

**Comment by telemarker** [comment]
i just tested it with an ipad ios8, same problem here.

**Comment by telemarker** [comment]
fixed it by using this video tag:
<video controls width="100%" poster="/poster.jgp" webkit-playsinline >

plays well in ios 8.3 for iphone and ipad.

**Comment by jeffikus** [comment]
cool thanks for submitting the fix, will keep a note in case this crops up again in future!
