### ISSUE TITLE
Wont install, or goes in Media

### ISSUE THREAD

**Issue by Celestialpetals** [woothemes/FlexSlider#1343]
Um, How do you install this zip to wordpress?

It is installing into my media files.  
http://i1197.photobucket.com/albums/aa424/yourzomgguide/woo_zpsqhwj5kok.png

**Comment by jeffikus** [comment]
Hi there

FlexSlider is just the javascript library, if you want to use it within WordPress you either have to include it in the code in your plugin or theme, or you can use the commercial plugin at http://www.woothemes.com/products/wooslider/

Thanks,
