### ISSUE TITLE
Flexslider 2.5 results into Bower version resolving error

### ISSUE THREAD

**Issue by isellsoap** [woothemes/FlexSlider#1344]
Since bower.json (and package.json) is only [a day old](https://github.com/woothemes/FlexSlider/commits/master/bower.json) , and thus also the explicit setting of a jQuery version, I think many projects using Flexslider with jQuery >= 2 as their basic jQuery version in their project have a problem, since Bower can’t resolve different major jQuery versions in one and the same project. See example image:

![bildschirmfoto 2015-05-28 um 14 20 32](https://cloud.githubusercontent.com/assets/477474/7859887/c7c3b4ee-0544-11e5-874e-4b032fc8ae21.png)

Could you at least set something like `"jquery": ">=1.11.3"`? In fact, that is a true statement, since we are using Flexslider with jQuery > 2.x for a very long time now. :-)

**Comment by evancarey** [comment]
I'm running into this issue as well. I'm also using angular-flexslider and jQuery 2.x and my build is busted because of the hard constraint on version 1.11.3. Please update. Thanks!

**Comment by DavidOliver** [comment]
+1. Thanks @isellsoap.

**Comment by NitroInside** [comment]
bower.json points to version `1.11.3`, but package.json to `^1.11.3`

**Comment by jeffikus** [comment]
Merged pull request #1346
