### ISSUE TITLE
IE7 compatibility issue

### ISSUE THREAD

**Issue by TreyTaylor** [woothemes/FlexSlider#1364]
Hey guys,

The notorious IE has struck again..

On a page with a flexslider loaded it pushes all the images down the page outside of the <div>

Here's an image to demonstrate what I mean:

![capture](https://cloud.githubusercontent.com/assets/8589670/8376226/a083bc2a-1bfc-11e5-9a95-e0d43c53e19d.PNG)

This is the div the flexslider is meant to stay inside, and then it ends up 2 divs below not in scale (the image) and all blurry..

it works on everything else except IE7 in a Windows Server 2003/Windows XP environment..

Is there any known workaround?

thanks :smile:

**Comment by jeffikus** [comment]
IE7 support is no longer provided unfortunately. Thanks.

**Comment by TreyTaylor** [comment]
@jeffikus Ahh I see, no worries :-) thanks :smile:

**Comment by jeffikus** [comment]
:) sorry!

**Comment by TreyTaylor** [comment]
No probs, I don't really see why people still use IE7 and below haha makes web dev just that little bit harder XD
