### ISSUE TITLE
Mobile slider shouldn't slide when = 1 slide

### ISSUE THREAD

**Issue by cclaro** [woothemes/FlexSlider#1371]
having a issue when the slider has one item and the user is still able to slide this one item.
here its my code:
$("#homeSliderMobile").flexslider({
                namespace: "mobileSlider-",
                selector: ".mobileSlider >.mobileSlide",
                animation: "slide",
                useCSS: "false",
                controlsContainer: "#homeSliderMobile",
                controlNav: "false",
                directionNav: "true",
                slideshow: "true",
                slideshowSpeed: "6000",
                animationSpeed: "1000",
                prevText: "",
                nextText: "",
                touch: "false",
                smoothHeight: true
                /*start: function() {
                    a(".desktopSlider > img").show()
                }*/
            })
      
        })

Thanks

**Comment by jeffikus** [comment]
Hi there. Why would you have a slider with 1 slide?

**Comment by alexwenz** [comment]
Same problem here. If you work with an CMS it would be nice to have the option to write the same code if its one or multiple slides. 
So the option "allowOneSlide" works fine with regard to the controls but on touch devices, users can swipe one image over and over again.

**Comment by cclaro** [comment]
Yes well described by @alexwenz its exactly what the problem is.

**Comment by jeffikus** [comment]
If you are working with a CMS then you should always check if the image number is greater than 1, then apply the slider, if not, simply output the image. Pretty much every WordPress plugin that uses Flexslider does it this way.

**Comment by alexwenz** [comment]
Hi jeffikus,
yes you are right. But why is there an option called "allowOneSlide"?

**Comment by jeffikus** [comment]
@alexwenz honestly not sure, probably introduced before my time, but i'll take a look anyway :)
