### ISSUE TITLE
allowOneSlide option seems miscoded

### ISSUE THREAD

**Issue by dymbox** [woothemes/FlexSlider#1372]
1170    if ( ( $slides.length === 1 && options.allowOneSlide === true ) || $slides.length === 0 ) {
                 // here comes the code for slider object won't get created
                 // however, allowOneSlide (true) option has opposite sense
           }
so, it should be

1170    if ( ( $slides.length === 1 && options.allowOneSlide !== true ) || $slides.length === 0 ) {
meaning, if the option is NOT set, object shouldn't get created

**Comment by jeffikus** [comment]
Will test next week - thanks for reporting.

**Comment by noahkuhn** [comment]
This is definitely broken. Took me forever to figure out why the direction arrows were showing up on a single slide (which they shouldn't by default even if flex slider is enabled), and then I discovered this parameter, but it doesn't actually work. An easy fix of one character, why haven't you pushed the change yet?
