### ISSUE TITLE
itemMargin not working

### ISSUE THREAD

**Issue by shahroq** [woothemes/FlexSlider#1373]
Hi,
It seems itemMargin does not working.

**Comment by jeffikus** [comment]
Hi there

Please provide a gist of your full code for context. Thanks.

**Comment by shahroq** [comment]
Hi,
At the demo/basic-carousel.html, changing itemMargin does not work either.

**Comment by stuporglue** [comment]
I'm also seeing this, even on the demo/basic-carousel.html. Here's a JSFiddle 

https://jsfiddle.net/6s9zaxc9/1/

**Comment by regepan** [comment]
@stuporglue :+1:  Good demo.

**Comment by jeffikus** [comment]
Thanks guys, have added to the milestone for testing.

**Comment by florianjacob** [comment]
So if I understand this bug right, itemMargin is actually intended to take care about the spacing itself?
From the documentation, I thought the property was only there to describe the margin you had set yourself with CSS.

For reference / until 2.6.0 is out, this is what I'm currently doing to get my margins:
https://jsfiddle.net/0czhk5eg/
It results in some unwandet behaviour though, as the ```itemMargins``` property is not taken into account when calculating whether all items fit in the viewport. See #1433.

**Comment by jeffikus** [comment]
Closed in #1434
