### ISSUE TITLE
New tag to use with Bower

### ISSUE THREAD

**Issue by NitroInside** [woothemes/FlexSlider#1377]
Hello,
The changes made due by Issue #1344 in PR #1346 are not  usable via Bower until a tag is generated. A tag is needed to have the fix via `bower.json`.

**Comment by jeffikus** [comment]
Fixed -> https://github.com/woothemes/FlexSlider/releases/tag/2.5.0

**Comment by NitroInside** [comment]
Thanks!

**Comment by jeffikus** [comment]
You are most welcome :)
