### ISSUE TITLE
Demo page animation freezes on Safari

### ISSUE THREAD

**Issue by bandrebandrebandre** [woothemes/FlexSlider#1379]
If you load up http://flexslider.woothemes.com/ on Safari and spend 5+ minutes clicking the controls and letting the animation run, the automatic animation will eventually freeze. The controls still work, but the automatic animation stops running.

I have Flexslider installed via the Drupal 7 module. https://www.drupal.org/project/flexslider With this module, the freezing happens much quicker, and the controls don't work either. I will be posting to the Drupal issue page as well, but I assume the ultimate problem is the WooThemes library.

I observed this behavior on two Macbook Pros running Safari 8.0.6 (10600.6.3) + Yosemite.

**Comment by jeffikus** [comment]
Hi there

Did you by any chance check if there were any errors in the debug console when this happens?

Thanks,

**Comment by bandrebandrebandre** [comment]
Yes. There were no errors.

**Comment by bandrebandrebandre** [comment]
I can create a screencap of the issue, if that would be helpful.

**Comment by jeffikus** [comment]
@bandrebandrebandre that would be great thanks, will help to replicate.

**Comment by bandrebandrebandre** [comment]
5+ minutes was an overstatement. It happens more quickly than that. 

Again, this isn't a big deal by itself, but with Drupal, it causes the controls to freeze as well as the animation to stop. So for Drupal users, it's a big deal.

Here's the vid: https://drive.google.com/file/d/0B3H7y8KKUpvBS3A1RUxHaUtJbW8/view?usp=sharing

**Comment by bandrebandrebandre** [comment]
Wait, sorry. Is it supposed to do that? Freeze the automatic animation after you use the controls?

**Comment by jeffikus** [comment]
ok i see what you mean, i'll debug further and get back to you - we had a similar issue in 2.4 release, but with hover pause. I'll check it out for the 2.6 milestone. thanks!

**Comment by jeffikus** [comment]
Cool, I've tested this extensively, I don't see any additional errors in the console in safari, and I haven't replicated this behavior, however, I will keep tabs on this in the future. There are a few demo fixes that have been committed, so once 2.6.0 has been released, I'd appreciate it if you could let me know if you still experience the issue. Demo fixes in #1382
