### ISSUE TITLE
Set tabindex to -1 for control paging on sliders

### ISSUE THREAD

**Issue by ksleyko** [woothemes/FlexSlider#1385]
It's detrimental to usability to have to tab through all the paging buttons before getting elsewhere on the page. Please set the tabindex to -1 for the control paging, either as a whole or each of the individual list items.

**Comment by jeffikus** [comment]
thanks, I have a few tabindex items for the milestone, so adding to it.

**Comment by jeffikus** [comment]
Resolved as part of #1368
