### ISSUE TITLE
demo css folder only contains demo.css

### ISSUE THREAD

**Issue by samseen** [woothemes/FlexSlider#1386]
In the index page, there are two files that references are made to they are: shCore.css and shThemeDefault.css. They both ought to be in the css folder. It neither affects performance nor does it cause any harm. If they're not necessary, I suggest they should be removed or added to the css folder.

**Comment by jeffikus** [comment]
Hi there

It's just for the demo site. the demo folder is just a demo, you can use and replace any of the components.

Thanks for the feedback though!
