### ISSUE TITLE
Slider does't pause on video play in Safari in demo

### ISSUE THREAD

**Issue by romulcah** [woothemes/FlexSlider#1388]
I haven't tested this in other browsers, but if you test the Vimeo demo:

http://flexslider.woothemes.com/video.html

Press play before first slide transition, the slider doesn't pause as per documentation indicates.

This issue is happening in Safari 6.1.6 on Mac OS X 10.7.5

**Comment by jeffikus** [comment]
Hi there

The wistia one works, it's possible vimeo have changed their API - will look into it.

Thanks for reporting, have assigned to the milestone!

**Comment by ross-mulcahy** [comment]
I've been playing around with this:

Here's my code:

	jQuery( document ).ready(function() {
 
      // Vimeo API nonsense
		 jQuery(function() {
			var iframe = jQuery('#player_1')[0];
			var player = $f(iframe);

			player.addEvent('ready', function() {
			    player.addEvent('play', onPlay);
			    player.addEvent('pause', onPause);
			    player.addEvent('finish', onFinish);
			});


			function onPause(id) {
			    jQuery('.flexslider').flexslider("play");
			}
			function onPlay(id) {
				alert("play");
			    jQuery('.flexslider').flexslider("pause");
			}

			function onFinish(id) {
			    jQuery('.flexslider').flexslider("play");
			}

		});
		 
		 
		  // Call fitVid before FlexSlider initializes, so the proper initial height can be retrieved.
		  jQuery(".flexslider")
		    .flexslider({
		      animationSpeed: 2000,
		      pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
			  pauseOnHover: true,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
		      touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
		      video: true,
		      useCss: false
		  });
	});

The "play" alert is called successfully but flexslider doesn't pause. Any idea?

Thanks,

Ross

**Comment by jeffikus** [comment]
The actual problem on the demo is that the player target was not correct - if you have http and https it wont work unfortunately.
