### ISSUE TITLE
I want to create slider like this (http://www.esolz.net/) using flex slider. is this posible ???

### ISSUE THREAD

**Issue by ajaykumarparashar** [woothemes/FlexSlider#1394]
I want to create slider like this (http://www.esolz.net/) using flex slider. is this posible ???

**Comment by jeffikus** [comment]
Sure you can, that actually is FlexSlider :D just heavily customized!

**Comment by ajaykumarparashar** [comment]
@jeffikus  will you please guide me on this i am working on OXYBEE.COM

**Comment by jeffikus** [comment]
Hi @ajaykumarparashar you can implement the default flexslider from the demo's and customize, unfortunately I'm not available to help with customizations. I would suggest hiring someone from something like Codeable or a freelancing site to get it customized.
