### ISSUE TITLE
Microsoft edge not detecting touch

### ISSUE THREAD

**Issue by Clearnine** [woothemes/FlexSlider#1400]
On Windows 10 in tablet mode, Microsoft Edge the control doesn't seem to detect touch.  The arrows don't appear and swipe doesn't work.  This all works fine in IE 10, 11 AFAIK.  It renders properly otherwise.

In desktop mode the buttons appear sometimes, usually not in full-screen.  

Edit: to see this behavior go to the flexslider.woothemes.com in Microsoft Edge.  For comparison install chrome on your surface.  Chrome behaves properly.

**Comment by jeffikus** [comment]
Hi there

I'm not 100% sure on our support policy regarding Microsoft Edge, I'm checking into it, will reply here ASAP!

Thanks for your patience in this regard.

**Comment by plkilroy** [comment]
I just tested on Surface (Win10), running Edge, same issue for me, any update, thanks!

**Comment by FM1973** [comment]
Any news regarding this problem? Thanks!

**Comment by jeffikus** [comment]
@FM1973 I'll look into this following the 2.6.0 release cycle which I'm currently busy with. thanks!

**Comment by frankyonnetti** [comment]
Hi @jeffikus, is there any updates for this issue? I'm guessing this is more of an issue with the Edge browser then it is with JS.

**Comment by frankyonnetti** [comment]
Nevermind @jeffikus, found this issue here: http://stackoverflow.com/a/34412315/896808
I guess touch is turned off by default in Edge.

**Comment by jeffikus** [comment]
Thanks for the feedback @frankyonnetti
