### ISSUE TITLE
https error created by Flexslider in Drupal 7

### ISSUE THREAD

**Issue by speckywestwood** [woothemes/FlexSlider#1404]
When I installed Flexslider on Drupal 7, the homepage that held the slideshow suddenly showed an https error in all browsers, with a warning triangle or other error icon.  Removing the Flexslider block from the home page stopped the error, ie the padlock appeared green again and clear of error messages.  Using Firefox and other browsers threw up there were mixed transmissions between http & https.  That meant that something in the Flexslider files had a web link such as http://www.example.com and not an https address.  I found a link to http://www.blogspot..... which was used by Flexslider to import the images for the navigation buttons for the slideshow in this file: sites/all/libraries/flexslider/flexslider.css on line 50 and line 59 (approx).  This file was downloaded from either Drupal Project or from Woothemes.  Taking out the url for blogspot resolved the issue.

**Comment by jeffikus** [comment]
Hi there. You need to first log the issue with the Drupal module developer - if it is Drupal then it would not have been downloaded from here. If the module developer finds the problem is within Flexslider then they should log the issue here.

Thanks,
