### ISSUE TITLE
Sync thumbnails move when clicking

### ISSUE THREAD

**Issue by bhambrabland** [woothemes/FlexSlider#1427]
Hello,

I have a setup with thumbnails being used in sync to control the main gallery but when you click on the thumbnails they move off screen to the left and I have to use the arrows to bring them back in to click on the next image.

The sync works perfectly, just the thumbnails move to far...

Any ideas?

Thanks kindly

**Comment by jeffikus** [comment]
Can you provide me with a live url of this happening? Thanks,

**Comment by bhambrabland** [comment]
Sorry this is resolved now, it was a series of custom CSS hidden in a theme that was causing the issues. All good now though.

Thanks

**Comment by jeffikus** [comment]
Awesome, thanks for letting me know :)
