### ISSUE TITLE
Last image is cut off when using a slider with itemMargin and all images fit on the screen

### ISSUE THREAD

**Issue by florianjacob** [woothemes/FlexSlider#1433]
itemMargin doesn't go in correctly in the computation of whether all images fit on the screen.

Example: https://jsfiddle.net/ycdn0Lpb/

**Comment by jeffikus** [comment]
Closed in #1434

**Comment by florianjacob** [comment]
@jeffikus tthis issue is not actually fixed. I [created a new fiddle with the current 2.6.0 branch](https://jsfiddle.net/mLczru8w/). I could delete my css declarations for the margins now, but the effect of images being cut of and the margin not being take into account when computing the visible witdth and wether navigation elements are needed is still there.
