### ISSUE TITLE
Nav arrows showing up as fi and fl

### ISSUE THREAD

**Issue by Baddeh** [woothemes/FlexSlider#1447]
Greetings, 

Trying flexslider for the first time and everything seems to work fine. When i roll over the images the nav arrows at the side are not arrows but letters that say "fi" on the left and "fl" on the right. 

Slider functions as it should, images slide. Any ideas on why the letter instead of arrows.

**Comment by jeffikus** [comment]
Hi there

Please can you provide a screenshot of what you are experiencing and/or a live url of the issue so I can check it out?

Thanks,

**Comment by roseofgold** [comment]
I'm not the OP and am working on the slider, but here's a link to what I'm seeing. Seems to be a similar issue.

http://flyingskull-net.3dcartstores.com/Insect-Images.html

**Comment by jeffikus** [comment]
Your CSS is missing the flexslider icon set, have you included all the font files?

**Comment by roseofgold** [comment]
Yup. The path to the font files was off in my css. Thanks for the second pair of eyes.

**Comment by jeffikus** [comment]
Glad it's sorted :) have fun!
