### ISSUE TITLE
Choppy transitions in Safari (mobile and desktop)

### ISSUE THREAD

**Issue by brianium** [woothemes/FlexSlider#1462]
Safari transitions are pretty choppy - images seem to flicker while transitioning. It seems to be related to large images being scaled (smaller images do fine).

I have a demo that should demonstrate the issue here:
http://brianium.github.io/flexslider-safari2-issues/

I tested this on Safari 8.0.7 on Mac OS X Yosemite and Safari 9 on iOS 9.1 (iPhone 6 plus)

**Comment by thomasguillot** [comment]
Looks like a browser limitation. Have you tried with `useCSS: false`?

**Comment by brianium** [comment]
Yes. It appears to be a limitation of Safari. `useCSS: false` appears to fix the issue for Safari, but it does not seem like an ideal solution to disable CSS3 transitions for every browser. Computers amirite? ¯\\\_(ツ)_/¯ - Thank you for looking into this though.
