### ISSUE TITLE
Flexslider Speed Control

### ISSUE THREAD

**Issue by fortislogo** [woothemes/FlexSlider#1464]
We have flexslider installed on this site http://aix.staging.wpengine.com. I need to control the speed when you are in slide 1 and then you jump to slide 4 or vice versa. Currently, the speed is fast and we want it to slow. What options should I checked.

**Comment by jeffikus** [comment]
Hi there, you want to try changing the 'slideshowSpeed' and the 'animationSpeed' - you can read up more here -> https://github.com/woothemes/FlexSlider/wiki/FlexSlider-Properties
