### ISSUE TITLE
Option pauseInvisible simply doesn't work

### ISSUE THREAD

**Issue by DelPoint** [woothemes/FlexSlider#1465]
Hi All,

I'm playing with your Flexslider for a few days long, but it seems to me the 'pauseInvisible' option simply doesn't do the job properly (or I've totally misinterpreted its objective). What I'm expecting if 'pauseInvisible' set to true:
- if the slider item outside of the viewport of the browser, it should stop the animation (tell me, if I'm wrong)

However, what happens: the slider continues to work. It is easy to test:
- just create a slider item at the beginning of any HTML page (with 'pauseInvisible' = true)
- add at least two slides
- ensure the slides height property different (because of their content is different)
- add some extra sections to the page _below_ the slider item to have a scrollbar in the browser
- launch the page
- scroll down a bit to push the slider item outside of the viewport
- & watch your page: it will 'breathe' (slowly moves down-up) as each of the slides (with different height) animated (which they ought not to do)

The above behaviour is a bit annoying as it renders the portion of the page below the slider item hard to read (as it continously scrolls up-down).

Cheers,

DelD.

**Comment by thomasguillot** [comment]
The `pauseInvisible` option will stop the slider if the user switches tab/window (or app). It's not meant to stop the slider if it's outside of the viewport
