### ISSUE TITLE
undefined variable when using strict mode

### ISSUE THREAD

**Issue by nckappeler** [woothemes/FlexSlider#1495]
```
Error: assignment to undeclared variable altText

**Comment by jeffikus** [comment]
@nckappeler feel free to submit a pull request if you are keen? let me know.

**Comment by nckappeler** [comment]
@jeffikus I'll have a look tonight

**Comment by nckappeler** [comment]
some more context: the issue happens when adding strict mode at top of the minified version. (In my case im using a taskrunner to merge all verndor scripts.)

**Comment by thomasguillot** [comment]
Fixed with #1531
