### ISSUE TITLE
I have 2 flexslider, the second one doesn't work, after resizing the inspector or the window, it does

### ISSUE THREAD

**Issue by Jhonan321** [woothemes/FlexSlider#1501]
i have a slider and its working good, 

![goodone](https://cloud.githubusercontent.com/assets/7134196/13225458/efb5bbc4-d95a-11e5-9faa-ba61c35a4b62.jpg)

but the second one, is a carrousel and does'nt resize correctly 
![before](https://cloud.githubusercontent.com/assets/7134196/13225648/b6bea83e-d95b-11e5-8c01-c9c99ddb79e0.jpg)

but if i inspect the element or resize the window, it takes the real size
![after](https://cloud.githubusercontent.com/assets/7134196/13225649/b6c6d220-d95b-11e5-892e-764af928b085.jpg)

how can i recalculate the size without resizing the window?

**Comment by tomaggio83** [comment]
I have the same problem. Please help me :-(

**Comment by tomaggio83** [comment]
I solved the problem using the plugin callback api:
`after: function(e){
    $(window).trigger('resize');
},
before: function(e){
    $(window).trigger('resize');
}`

I put theme right after the plugin options.

I hope this can help you.

**Comment by Jhonan321** [comment]
Hey @tomaggio83, thxn for solution, i didn't know that plugin and surely i ll have to use it some time, i solved the problem giving a width to the flexslider container, i only had a max-width... crazy, isn't it? ¬¬
