### ISSUE TITLE
Flexslider in Bootstrap Grid - Bug

### ISSUE THREAD

**Issue by MichaelRise** [woothemes/FlexSlider#1526]
Hey,

I use FlexSlider in Bootstrap grid - 4 columns.
When I use `animation: 'fade'` grid its OK, but when I use `animation: 'slide'` grid its broken.

Animation fade - [https://jsfiddle.net/s8etezf5/](https://jsfiddle.net/s8etezf5/)
Animation slide - [https://jsfiddle.net/s8etezf5/1/](https://jsfiddle.net/s8etezf5/1/)

How to use "slide" animation in grid ?

Please help.

Have a Nice Weekend
Michael

**Comment by MichaelRise** [comment]
Hey,

Please Help. I don't know how I can fix it.

Thanks
Michael

**Comment by MichaelRise** [comment]
Hey,

I'm using jQuery (v1.12.3) and Flexslider (v2.6.1). All of jQuery's width methods seem to be rounding-off the value of the width - https://jsfiddle.net/syuudd9L/

For example if the actual width of an element was `20.333333px`, jQuery's width method returns `20`, i.e ignoring the decimal value - http://jsfiddle.net/tfq9vjwb/

Please help me.

Thanks
Michael

**Comment by MichaelRise** [comment]
Any progress ?

**Comment by jeffikus** [comment]
Hi there

Afaik the .width() method will always return an integer, so it will always be rounded off unfortunately.

**Comment by f7n** [comment]
Same problem. multiple Flexsliders in a grid causes layout problems. my boss is killing me because of this bug.
