### ISSUE TITLE
slider not working only on safari

### ISSUE THREAD

**Issue by tykayn** [woothemes/FlexSlider#1527]
hi, i have setup a flexslider on www.latrotteuse.fr but i cant figure out why it doesnt work only on safari. the sliders keeps on having its height at 0 px, but the safari console outputs no error about that.
do you have any idea why it would do that only on safari ?

**Comment by jeffikus** [comment]
hi there

first thing to do here is update your flexslider to the latest version - 2.6.0 - as you are currently running 2.5.0 on the site.

thanks,
