### ISSUE TITLE
Go back to the top of the page (bug)

### ISSUE THREAD

**Issue by ByteSupreme** [woothemes/FlexSlider#1528]
Hello everyone,

I have a problem on IE11 on W8 & 10 (**not edge**).  When i click on the "years field" (http://puu.sh/oEJi2/0a9fe956af.png), i go back to the top of the page and # is added in the URL. (maybe a anchor problem ?)

Normaly, it changes the current slide for the one matching with the slide of the year selected. Also, the slider works perfectly on my IE11 & W7 and Chrome/Firefox/Safari ... The plugin is the 2.5 version and i can't change for the moment.

I tried to change pieces of code considerates deprecated by microsoft (here :  https://msdn.microsoft.com/en-us/library/dn304886(v=vs.85).aspx) for IE11 but it changed anything. I use the plugin on a drupal site (ver 7.x).

Any solutions ? 

Thanks !

**Comment by jeffikus** [comment]
Hi there

You would need to first update to 2.6.0 before I can properly debug this. You would need to ask the plugin developers to do this. 

Please reopen the issue once you've updated so I can take a look.

Thanks,
