### ISSUE TITLE
flexslider fi/fl instead of arrows navigation

### ISSUE THREAD

**Issue by levinz** [woothemes/FlexSlider#1539]
i am using flexslider 2 in the header of this site: http://skiss.electricalenergy.se/ The arrows just stopped showing properly. Instead I got letter FL/FI. The flexslider.css links to the font folder. So I do not understand what is the problem here?

**Comment by Bluetegu** [comment]
This happens when it can't find the font. Verify the url(s)l in the css file are reachable.

**Comment by jeffikus** [comment]
@levinz seems to be working fine on that site. @Bluetegu please make sure you are using the latest version of Flexslider and provide a url of the issue. Thanks.
