### ISSUE TITLE
Flexslider 1.x branch is now gone

### ISSUE THREAD

**Issue by eizzumdm** [woothemes/FlexSlider#1540]
Is there any reason why the 1.x branch of Flexslider was deleted? The make file for the Flexslider 1.x module for Drupal relies on this library:

; Retrieve flexslider v1 from github
libraries[flexslider][download][type] = "get"
libraries[flexslider][download][url] = "https://github.com/woothemes/FlexSlider/zipball/flexslider1"
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

The General Notes for this repo still reference Flexslider 1.8:

"In an effort to move the plugin forward, support for jQuery 1.4.2 has been dropped. The plugin now requires jQuery 1.7.0+. If you don't have access to the later versions of jQuery, [FlexSlider 1.8](https://github.com/woothemes/FlexSlider/tree/flexslider1) should be a perfectly suitable substitute for your needs!"

**Comment by jeffikus** [comment]
Flexslider 1.8 is an extremely old version. We do not support that, I have noted though that 1.8 is mentioned in the readme - I will update the docs to reflect things correctly. For example, version 2.1 was released in 2012, so 1.8 support is not something we will be pursuing going forward as it's more than 4 years old.

[NOTE: FIX DOCS]
