### ISSUE TITLE
Received 'invalid-meta' notice on Bower install

### ISSUE THREAD

**Issue by badfeather** [woothemes/FlexSlider#1546]
Upon Bower installation, I received the following:
```
bower flexslider#*              cached https://github.com/woothemes/FlexSlider.git#2.6.0
bower flexslider#*            validate 2.6.0 against https://github.com/woothemes/FlexSlider.git#*
bower flexslider#*                 new version for https://github.com/woothemes/FlexSlider.git#*
bower flexslider#*             resolve https://github.com/woothemes/FlexSlider.git#*
bower flexslider#*            checkout 2.6.1
bower flexslider#*        invalid-meta The "main" field cannot contain globs (example: "*.js")
bower flexslider#*            resolved https://github.com/woothemes/FlexSlider.git#2.6.1
bower flexslider#^2.6.1        install flexslider#2.6.1
```
It looks like it still installed fine. Just thought I should let you know.

**Comment by jeffikus** [comment]
Thanks for reporting, will take a look.

**Comment by mikemad** [comment]
This is annoying and causes a big red blotch in our build results. Please fix.

**Comment by jeffikus** [comment]
I fixed the build manifest and works fine now. The font's in the "main" spec were causing the issue.

@mikemad next time please submit a pull request if you know what a possible fix is - like @badfeather mentions above, it does install correctly, it simply fires a warning message. I'd appreciate any pull requests as it speeds up the process.

**Comment by mikemad** [comment]
Sounds good. Awesome!
