### ISSUE TITLE
no arrows with flexslider and firefox (newest version)

### ISSUE THREAD

**Issue by be-sign** [woothemes/FlexSlider#1558]
hi flexslider-team,

there are no arrows with flexslider 2.6.1 and firefox 47.0.1 on mac os 10.7.5 and mac os 10.11.5
can only see a little box filled with "F001" and "F00". all other browsers will show the navigation arrows.

what can i do to fix this? i want to replace my old adobe edge-animate portfolios with felxslider, because its much more easier to administrate and looks cool. at this point: thanks for this fine tool.

bernd

**Comment by jeffikus** [comment]
Can you provide a URL for me to see this on?

**Comment by be-sign** [comment]
i try to mangae it. its not complete, so it is only local on my computer. i will write back...

**Comment by be-sign** [comment]
thanks for your question - ist was also a solution :-)
at the moment, the page is online, firefox will show the arrows correctly.

http://www.be-sign.net/pages/se/SeShow_flexslider_demo.html

but there is one open question: why doesnt it work, when i show the page local on my computer? is this a firefox-issue, or is it an general problem with using external fonts?

tanks!

**Comment by jeffikus** [comment]
If you are pulling in external font files, then yeah you would need to be online :)
