### ISSUE TITLE
Fade effect broken in v2.6.2

### ISSUE THREAD

**Issue by Chrez** [woothemes/FlexSlider#1574]
When fading slides with the normal structure .flexslider > .slides > li > img , the images don't fade one over another, but first the visible fades out and after some time the next one fades in. So there is a gap in which the background is seen.

It comes from the new version, because whenever i switch my js file to v2.6.1 it's ok.

**Comment by jeffikus** [comment]
Please supply a URL so I can take a look.

**Comment by Chrez** [comment]
Well im working on that project and i dont have the time to do it. 
I think that you can test it by yourself. Without touching anything on js, css or the default structure.

**Comment by jeffikus** [comment]
@Chrez I wouldn't ask you for a URL if I could replicate on my end. Please reopen this when you have the URL or a screencast of what you are experiencing, as I've tested on the demo's with fade with no issues.
