### ISSUE TITLE
Fade Animation Harsh in 2.6.2

### ISSUE THREAD

**Issue by emmills3** [woothemes/FlexSlider#1578]
The recent updates to the fade animation has created a much harsher transition. The transition in 2.6.1 and previous versions is much smoother. Toggling useCSS has not effect.

**Comment by jeffikus** [comment]
Can you provide me with a URL so I can take a look?

**Comment by emmills3** [comment]
Version 2.6.2:
http://staging.awpserver.com/z_test/flexslider/demo/index.html

Version 2.6.1 (to compare):
http://staging.awpserver.com/z_test/flexslider/demo/previous.html

**Comment by sterndata** [comment]
I can show the same thing -- the home page at http://newirisb.sterndata.com.  I just updated to 2.6.2 and no matter what I set for easing or animation speed, it just flicks the slide out.

**Comment by jeffikus** [comment]
Thanks guys, will prioritize this today.
