### ISSUE TITLE
Carousel with variable width of the items

### ISSUE THREAD

**Issue by ninetienne** [woothemes/FlexSlider#245]
Is there a way to make the carousel with variable width of the items? 

```js
$('.flexslider').flexslider({
    animation: "slide",
    directionNav: true,
    animationLoop: false,
    itemWidth: 'variable', // this is the suggested syntax
    itemMargin: 5,
    move: 1
});
```

**Comment by regeisle** [comment]
Curious if there's an update on this?  I saw a few mentions of it being in 2.2.2 up the thread some but not in there from what i can tell.  Still would love to see this as a feature.  Right now we're using Galleria for real estate galleries:  http://agent615.gydev.com/1585490   Works ok, but responsive still gets a little hard to control.  Would love to switch to flexslider for these but too much variation in thumbnail size to do that as is.

I also have to comment on how incredibly rude some of these people are...   1) this is a free plugin, 2) no one is forcing you to use it and 3) there are countless other slider/carousel plugins you can use.  Wouldn't it be easier to just switch to one of those than continue to complain to and criticize those who are working on this as an open-source project?

**Comment by smujohnson** [comment]
@mattyza

The use case for having variable width items is simple:  not all images of products (to use an example) have the same horizontal width.

See:  http://i.imgur.com/hXZci8l.png

This is Amazon's slider.  Notice the bottle of lotion is thinner than say the FireTV.

**Comment by yiikoma** [comment]
**I made it work with this little hack:**
_in your view, where you init the flexslider call the resize method after init like this:_
`setTimeout(function() {
            $('.flexslider').resize();
        }, 500);`

_In the flexslider core update the resize method:_
```
resize: function() {
        if (!slider.animating && slider.is(':visible')) {
           
           // set image sizes to auto
           $(".flexslider img").css("width", "auto");
             
           var countImages = 0;
           var sumImagesWidth = 0;
           
           // walk over images in slider, count the images and calc the median of those pics
           $('.flexslider img').each(function(i, obj) {
              sumImagesWidth = sumImagesWidth + $(obj).width();
              countImages++;
          });
             
          if (!carousel) slider.doMath();

          if (fade) {
            // SMOOTH HEIGHT:
            methods.smoothHeight();
          } else if (carousel) { //CAROUSEL:
            
            // set new median value   
            slider.vars.itemWidth = sumImagesWidth / countImages;
          
            slider.slides.width(slider.computedW);
            slider.update(slider.pagingCount);
            slider.setProps();
            
          }
          else if (vertical) { //VERTICAL:
            slider.viewport.height(slider.h);
            slider.setProps(slider.h, "setTotal");
          } else {
            // SMOOTH HEIGHT:
            if (slider.vars.smoothHeight) methods.smoothHeight();
            slider.newSlides.width(slider.computedW);
            slider.setProps(slider.computedW, "setTotal");
          }
          
          // set the <li>-tags around the pics to auto width
          $(".flexslider li").css("width", "auto");
        }
      },
```

# worked for me like a charm

**Comment by HandHugs** [comment]
@yiikoma can you provide a jsfiddle of this working? Are there any settings in CSS that we need to change to get this to work?

**Comment by css-wizard** [comment]
Hello friends, I wrote this simple solution and it works flawlessly.

`$(window).load(function() {	
	total_width = 0;
	$('.slides > li').each(function() {
		total_width+=$(this).width();
	});
	avg_width = total_width / $('.slides > li').length;
  $('.flexslider').flexslider({
    animation: "slide",
    animationLoop: true,
    itemWidth: avg_width,
    itemMargin: 0,
	controlNav: false
  });
});`

**Comment by gnarmedia** [comment]
it'd be nice if @css-wizard's solution could be added to the docs as I can see this has a decent amount of requests

**Comment by jeffikus** [comment]
@gnarmedia noted, thanks!
