### ISSUE TITLE
FlexSlider crashes IE7

### ISSUE THREAD

**Issue by jkapaldo** [woothemes/FlexSlider#269]
Hi,

I am building a homepage that includes a calendar carousel coming from an RSS feed. I have placed a FlexSlider inside of the rss reader jquery plugin. It seems to work everywhere, but IE7. Is this a FlexSlider issue? or is it my coding?

See example: http://enews.andover.edu/q/v2/

Many thanks,
Jonathan

**Comment by jeffikus** [comment]
Hi there

Unfortunately IE7 is deprecated and no longer supported going forward.

Thanks,
