### ISSUE TITLE
FlexSlider v2.1 full screen slides and browser resize problem

### ISSUE THREAD

**Issue by lumix1991** [woothemes/FlexSlider#280]
Dear,

I use FlexSlider v2.1 for sliding full screen slides. When I open a page with the full screen slider on it, the slider works perfectly (also on ipads etc).

When I resize the opened browser to a smaller size (smaller width) the width of the slides stay at the width that was set on the DOM load. Result, a slider that partially falls-off the page.

BUT

When I resize the browser to a LARGER size (larger width) the width of the slides are adjusted to the new browser width, result a slider that fits perfectly on the smaller browser page.

TO CLARIFY

This problem only occures when i resize the browser to a smaller width.

Thanks!

**Comment by Viriathus** [comment]
I have the same problem here :'(

**Comment by eriku** [comment]
FYI: I had this problem and the problem ended up being that the <body> element has `display: table;` on it. Not a flexslider issue but a css one.
