### ISSUE TITLE
Infinite / Circular Loop

### ISSUE THREAD

**Issue by jconroy** [woothemes/FlexSlider#287]
Hi Tyler - quick question (maybe needs to be explored offline) What would it take to get the infinite / circular loop functionality implemented? Or at the very least a hacky add-on?

**Comment by tjdurden** [comment]
+1 too! This would be a very useful addition.

**Comment by tjdurden** [comment]
In fact, any code examples or workarounds for this would be most appreciated.

**Comment by yves-s** [comment]
The only workaround I found was using another slider. In my case I used [Slick slider](https://kenwheeler.github.io/slick/)

**Comment by trlarson** [comment]
How has this not been fixed yet? :-1:

**Comment by daslicht** [comment]
Just use another spider, there are plenty out there which can do even more...

**Comment by cannect** [comment]
@daslicht Name them! :-)

**Comment by yves-s** [comment]
Just use [Slick Slider](https://kenwheeler.github.io/slick/) @cannect

**Comment by daslicht** [comment]
Even the example is circular..: http://flexslider.woothemes.com/

**Comment by yves-s** [comment]
Didn't you mentioned it already as well because in an earlier answer I referenced to you. [An earlier answer of me](https://github.com/woothemes/FlexSlider/issues/287#issuecomment-54132573)

**Comment by cannect** [comment]
@yves-s Thank you! I got that one on my favorite list. To use it in my next project :)

**Comment by Taiger** [comment]
Flexslider doesn't support infinite carousels. It would be nice if that was documented somewhere.

**Comment by Jomes87** [comment]
For everyone who is looking for an infinite looping carousel, I've just found this: http://kenwheeler.github.io/slick/

**Comment by libinemmanuel** [comment]
If we are not setting "itemWidth" then infinite loop will work.

![untitled-1](https://cloud.githubusercontent.com/assets/4044573/7998873/7160dcae-0b60-11e5-93ab-93723ce4760c.jpg)

**Comment by ashishkatoch** [comment]
This code is working for circular infinite loop.  :)

 jQuery('#product-img-slider').flexslider({
               slideshowSpeed: 2000,
                animationDuration: 800,
                animation: "slide",
                directionNav:true,
                controlNav:true,
                animationLoop: true,
                slideshow:true,
});

**Comment by crmb** [comment]
thanks for the slick info. the infinite carousel works properly.

**Comment by Julix91** [comment]
@jeffikus milestone was 2.6, which is now in the past. Was this implemented / is there currently an "open" topic on this somewhere?

**Comment by cbratschi** [comment]
An endless mode would be useful. But this mode should also repeat items if there are too few. The examples above did not work.
