### ISSUE TITLE
basic carousel not loading

### ISSUE THREAD

**Issue by xacarias** [woothemes/FlexSlider#343]
Im using Flexslider and jquery mobile for my project.  The problem is that every time i go to other pages of the mobile site the basic carousel is not loading. I have to refresh the page see it.  

Can you please help me with this issue.. Thank you very much :)

**Comment by AnastasiaVays** [comment]
Any solution? I am having the same problem http://sc.com.ly/show/mw1MSBZpI4lC7UVq9esOcJtQH5h3kTXo...Thanks.

**Comment by AnastasiaVays** [comment]
Any solution? I am having the same issue. Here is what happens: http://sc.com.ly/show/mw1MSBZpI4lC7UVq9esOcJtQH5h3kTXo
