### ISSUE TITLE
multiple item vertical slider doable?

### ISSUE THREAD

**Issue by cibgraphics** [woothemes/FlexSlider#359]
I am trying to more or less do a text slider (list of names/position), and I want them to scroll vertically showing 6 and 12 items at a time (I have two).  I tried to rig this up using all the options but could really only get one to show... or if I did get more to show, it would act funny and you could visibly see objects being added. (wish I could show you something, but its a private project).  Is this within the scope of this plugin? 

The closest that I have done is using the jCarouselLite plugin, but there is no destroy method. I need the  JS to be destroyed when it goes to mobile because the layout view calls for multiple columns done with css and I dont think any plugin in the world can do that.

Sorry if it is a little vague.

This is a screenshot. http://i47.tinypic.com/2uh1ens.png

**Comment by huykon** [comment]
not working
