### ISSUE TITLE
flexslider(0) on the last slide

### ISSUE THREAD

**Issue by ddramer** [woothemes/FlexSlider#369]
Hi!
Thank You for the plugin!
Im having issues with calling $('myselector').flexslider(0) on the last slide, it doesn't work. 
Also it doesn't work to call last slide from any slide. $('myselector').flexslider(3) in my case.

However it does work if I use the native navigation numbers or prev/next to navigate to last slide and to home from there.

Using the latest commit code You have submitted.
Can you help?

**Comment by Julix91** [comment]
0 doesn't work because it's falsy - "0" does work however! :)
