### ISSUE TITLE
IE7 + Fade issue

### ISSUE THREAD

**Issue by kjetterman** [woothemes/FlexSlider#387]
Hello,

I am having an issue with my slider in IE7.  When it fades in/ out to reveal the next slide, the previous slide drops down. 

Any solutions to this?

Here is my site for reference so that you can see what I mean:  http://diocesan.com/testsite

TIA for your help!! :)

**Comment by jeffikus** [comment]
Hi there

Unfortunately IE7 is deprecated and no longer supported going forward.

Thanks,
