### ISSUE TITLE
Manual re-initiate flexslider

### ISSUE THREAD

**Issue by smallmck** [woothemes/FlexSlider#391]
I´m missing opportunity to re-initiate flexslider after container is resized. That´s why my slides are´t horizontally centered. 
Is there quick way how to fix it? 

Flexslider is only re-initiated after window resize...

Thanks

**Comment by rajeshaspl** [comment]
Hi ,

Please guide me asap.
I have below code but it could not work when mobile orientation (resize) the window.
function initFlexSlider() {

jQuery('#flexslider-5').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 100,
    itemMargin: 14,
    asNavFor: '#flexslider-4'
  });
   
  jQuery('#flexslider-4').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#flexslider-5"
  });
}

Thanks
