### ISSUE TITLE
100+ slide items on Flexslider crashes on iPad

### ISSUE THREAD

**Issue by johnysusanto** [woothemes/FlexSlider#415]
I tried having around 100+ slide items using Flexslider and it seems to crash iPad all the time.
There seems to be a memory usage issue.

I tried loading only 1 image at a time, so it'll only load the image on display. 
But this also couldn't stop it from crashing.

**Comment by RwwL** [comment]
Here's a minimal test case in case anyone ever decides to re-open this and dig deep. This Flexslider has 50 items, and it crashes the tab consistently in Mobile Safari iOS 9.3.4 (current at the time of this post). 

Important to note that the crashing only occurs on actual hardware, not the iOS simulator provided with XCode.

http://s.codepen.io/RwwL/debug/xOmmym
