### ISSUE TITLE
How to trigger flexslider redraw?

### ISSUE THREAD

**Issue by nathanielks** [woothemes/FlexSlider#424]
I've got a page with multiple sliders, one per element (9 elements total). They're in a container that can switch between two views, grid and list. Two buttons fade the view element out, add a class to it, then fade it back in to display the updated layout. When it fades in with the new class applied, the slider images still have the previous view's widths applied to them. How can I trigger flexslider to recalculate the widths of the slider elements so that they fit inside the updated view?

Sadly I can't provide any code, but I'd be happy to provide further explanation if necessary.

**Comment by Jalliuz** [comment]
I also had the problem with the flexslider that behaves weird. For me the solution was to have the closest wrapper div to be display: block; (before it was inline-block)
