### ISSUE TITLE
{animation: "fade"} + slider.addSlide() + iOS = blank slides

### ISSUE THREAD

**Issue by dameian** [woothemes/FlexSlider#446]
Setting {animation: "fade"} then dynamically adding new slides via slider.addSlide() during runtime on iOS devices produces a blank slide for any new slides added. It works fine when using {animation: "slide"} though. 

Any ideas?

**Comment by bradbamford** [comment]
Just ran into this issue using Chrome on the Desktop.
Changed animation from Fade to Slide fixed it, but clearly still a bug.

**Comment by jeffikus** [comment]
@bradbamford can you upload a short screenshot and reopen the issue?
