### ISSUE TITLE
Flexslider 1.8: All caption shown at once in IE10

### ISSUE THREAD

**Issue by stroetpa** [woothemes/FlexSlider#458]
I ran into a problem using IE10 on Windows 8, the app version and the desktop version.

All captions are shown on top of each other.

It works well with Chrome on Windows 8 and IE10 in WIndows 7.

Any ideas?

**Comment by mattyza** [comment]
Hi @stroetpa.

I'd recommend using the latest version of FlexSlider, as version 1.8 is no longer supported.

The latest version can be found here: http://github.com/woothemes/flexslider/releases/latest/

Thanks! :)
