### ISSUE TITLE
Vertical thumbnails

### ISSUE THREAD

**Issue by friendlyweb** [woothemes/FlexSlider#491]
Hi there,
Thank you for a great plugin.

What I am trying to create is a vertical carousel that links in to a bigger version that thumbnail.

so what i want to do is this
http://flexslider.woothemes.com/thumbnail-slider.html 

but have the thumbnails vertical

If anyone can help me that would be amazing !
Thank you so much i look forward to your reply's. 
Karl

**Comment by huykon** [comment]
any solution ?

**Comment by azerphoenix** [comment]
Hi,
To link to a bigger version of thumbnail you must add another script. For example - Magnific popup (recommended).
For example ro create horizontal slider with the same functionality you must do this (Example shown in WP):
- in functions.php add by using wp_enqueue_script scripts & styles of flexslider & magnific popup scripts.
- create a js file enqueue it too in functions.php and add this code:
`/* FlexSlider */
jQuery(window).load(function() {
  jQuery('.flexslider').flexslider({
    animation: "slide",
    animationLoop: false,
    itemWidth: 210,
    itemMargin: 5
  });
});


/* magnific popup */
jQuery(document).ready(function($) {
    $('a[href*=".jpg"], a[href*=".jpeg"], a[href*=".png"], a[href*=".gif"]').each(function(){
        if ($(this).parents('.gallery').length == 0) {
            $(this).magnificPopup({
                type:'image',
                closeOnContentClick: true,
                });
            }
        });
    $('.gallery').each(function() {
        $(this).magnificPopup({
            delegate: 'a',
            type: 'image',
            gallery: {enabled: true}
            });
        });
    });
 
`
- in your template add this code:
`
							<?php
							$images = get_field('img_carousel');
							if( $images ) { ?>


								<div id="carousel" class="flexslider">
									<ul class="slides gallery">
										<?php foreach( $images as $image ): ?>
											<li>
												<a href="<?php echo $image['url']; ?>"><img src="<?php echo $image['sizes']['thumbnail']; ?>" alt="<?php echo $image['alt']; ?>" /></a>
											</li>
										<?php endforeach; ?>
									</ul>
								</div>
							<?php
							}else{
							?>
							<div id="single-gallery-image">
								
								<?php $featured_img_url = get_the_post_thumbnail_url(get_the_ID(),'full'); 
								echo '<a href="'.esc_url($featured_img_url).'" rel="lightbox">'; 
									the_post_thumbnail('medium');
								echo '</a>';?>
							</div>
							<?php } ?>
						`

> This example shows how to add flexslider with popup to the posts (single.php) and add images via ACF + ACF Gallery.
