### ISSUE TITLE
When the Download Builder will be available?

### ISSUE THREAD

**Issue by ghost** [woothemes/FlexSlider#578]
Hello,

Since Flexslider 2, the library has gained a lot of weight, and for the many people who just need a simple slider without all the extra features there is no possibility to have a lightweight version of the slider, which does only one thing: slides <li> blocks.

You could simply answer to use Flexslider 1.8, and this is what many of us have been doing, but as there are more and more touch-enabled-devices-running-windows users, we have no choice but to use the latest Flexslider (which by the way doesn't seem to fully work on those yet).

You have promised to release a "Download Builder" soon after the release of Flexslider 2.0 a while ago and still not sign of such tool.

Instead of a Download Builder, perhaps you could simply offer a light version, which does not have ANY feature at all (not even the API itself in order to save as much bytes as possible) but to have the only ability to actually slide stuff, using mouse cursor or finger, nothing more nothing less.

Thank you for your work.

**Comment by mattyza** [comment]
Hi there,

We've thought about this one for a while and feel it's best for us to focus on keeping the FlexSlider library as light as possible, generally. Building a tool to make it lighter won't serve the interests of all FlexSlider users, in our view.

One feature we are exploring is integrating a Grunt or Gulp file, for streamlined customisation.
