### ISSUE TITLE
Resizing carousel elements before recalculating?

### ISSUE THREAD

**Issue by Lemmork** [woothemes/FlexSlider#600]
Hi, 
I created a carousel with version 2.2, like described in this example:
http://flexslider.woothemes.com/dynamic-carousel-min-max.html

After resizing the elements have the wrong width. I looked into the code and inside the resize method, the width of the slides is set before the values are updated/recalculated. If I change the order in lines 471-473 from
slider.slides.width(slider.computedW);
slider.update(slider.pagingCount);
slider.setProps();

to

slider.update(slider.pagingCount);
slider.setProps();
slider.slides.width(slider.computedW);
            
, it works for me.

Regards
Heiko

**Comment by xbroak** [comment]
Why was this closed? is there a fix?

**Comment by jeffikus** [comment]
@xbroak http://develop.woothemes.com/flexslider/2015/03/18/flexslider-future-forecasting/
