### ISSUE TITLE
Images cut off in slider

### ISSUE THREAD

**Issue by krisscross90** [woothemes/FlexSlider#604]
The images in my slider don't seem to fit flush within the slider and so on each page move some of the images are half on one page and half on the next page. 

Here's an example http://www.test.vbs4u.com/vbs2013/portfolio/ 

If anyone could help me or direct me to another post that has the same issue I would greatly appreciate it.

![portfolio](https://f.cloud.github.com/assets/1529983/297740/87710778-9545-11e2-8a04-c5304dc46627.jpg)

**Comment by sGambolati** [comment]
I'm having the same issue. There is any solution or workaround?
Thanks!
