### ISSUE TITLE
Bug? Carousel With Min & Max Ranges: Not working!

### ISSUE THREAD

**Issue by CourtFantinato** [woothemes/FlexSlider#646]
Hello,

I am using the code from the Carousel With Min & Max Ranges: http://flexslider.woothemes.com/dynamic-carousel-min-max.html

I am getting the error: "Uncaught TypeError: Cannot read property 'vars' of undefined"
As well as: "Uncaught ReferenceError: SyntaxHighlighter is not defined"

I have noticed on the link above, that the example is also getting an error: "Uncaught TypeError: Cannot set property 'minItems' of undefined"

The number of items shown when resizing does NOT change as well, on both mine and the example, it only does on refresh. So the window resize is not working.

Has anyone else noticed this and come up with a solution?

Thanks!

**Comment by aaron-straker** [comment]
@mimpho That solved my issue as well. The example here: http://flexslider.woothemes.com/dynamic-carousel-min-max.html has flexslider defined as a local variable which was not working for me.

**Comment by nsickness** [comment]
I have solved this problem this way:

var $window = $(window),
    flexslider = { vars:{} };

**Comment by jeffikus** [comment]
Ok, seeing as quite a few people have commented here, I think it warrants reopening for further investigation. I've marked it for the 2.6.0 release.  I appreciate all your comments, thanks guys!

**Comment by eduarroyo05** [comment]
I was experimenting the same issue. The solution of @nsickness works for me.

**Comment by channabasappa** [comment]
flexslider is not working properly when orientation in ipad from portraits to landscape and vice-varse.

**Comment by channabasappa** [comment]
flexslider is not working properly when orientation in ipad from portraits to landscape and vice-varse.

Please give suggestions
