### ISSUE TITLE
Issue #130 not resolved

### ISSUE THREAD

**Issue by MrPaulDriver** [woothemes/FlexSlider#663]
First time posting on GitHub and not quite sure of etiquette or how to reopen a closed issue, hence posting here as a support request instead of new bug report.

I am finding problems with IE7/8 as discussed here... https://github.com/woothemes/FlexSlider/issues/130

I am using the latest release and find that the issue with IE7/8 displaying the back and next buttons outside the container seems not to be resolved. Please see screen shot.

Any pointers much appreciated

![flexslide-nav-bug](https://f.cloud.github.com/assets/3405783/474092/8400c28c-b75e-11e2-9271-d3d780d55284.jpg)

**Comment by jeffikus** [comment]
Hi there

Unfortunately IE7 is deprecated and no longer supported going forward.

Thanks,
