### ISSUE TITLE
Flexslider conflict with Twitter Bootstrap

### ISSUE THREAD

**Issue by krisztinatoth** [woothemes/FlexSlider#678]
Hi all!

I came across a very weird issue when trying to integrate Flexslider with the latest version of Twitter Bootstrap. The slider is working flawlessly on desktop, the problems arise when viewing the page on mobile, specifically iOS.

The problem is when I open Bootstrap's main navigation and use touch events on the slider, the navigation items start highlighting and flickering like they were hovered over or selected.

I thought this is a CSS issue at first, but after a lot of research I found a few Bootstrap themes which present the exact same behavior. Please have a look at two of them:
http://responsivewebinc.com/premium/metro/lblue/
http://www.leonart.gr/htmlthemes/restart_v1.1/index.html

I tried switching from 'slide' effect to 'fade' and also setting useCSS to false. I even removed "-webkit-backface-visibility: hidden;" as suggested in similar threads but to no avail, the problem still persists.

Please if you can think of a solution for this issue I'd love to know, this is a great slider and I'm very happy with it except this issue.

Thank you very much!
Krisztina

PS: Other pages on the same website do not have this problem, only the one with the slider on it.

**Comment by jeffikus** [comment]
Thanks, I've assigned for testing in the 2.5.0 release cycle.

**Comment by jeffikus** [comment]
I've tested in Safari and Chrome on iOS 8 and cannot replicate the issue, please provide a screencast and reopen the issue if it persists for you. Thanks.
