### ISSUE TITLE
Want to make the flexslider standing.

### ISSUE THREAD

**Issue by zohaibmomin** [woothemes/FlexSlider#699]
By default the demos I have used have flexslider carousel horizontal. Since I am using for mobile apps too I need a carousel which is standing i.e 'Up' arrow and 'Down' arrow would behave like 'prev' and 'next' respectively.

Using the direction:'vertical' gives some other feature all together.

Please help me on this.

**Comment by mattyza** [comment]
Hi @zohaibmomin.

The latest version of FlexSlider, with `carousel` enabled and `direction: vertical` provides a vertical carousel.

Thanks! :)
