### ISSUE TITLE
Did WOOTHEMES kill FlexSlider?

### ISSUE THREAD

**Issue by ghost** [woothemes/FlexSlider#725]
Ever since the acquisition of FlexSlider by WooThemes, it did not get any update :-1: 

The version 2, which was released a year ago, was a generous contribution offered by Tyler Smith, but beside that, WooThemes did not actually take over the project at any point.

Buying a software to bury it and leave it die slowly by just letting its obsolescence take over is a very bad ethical practice. It is not a secret from anyone that WooThemes purchased FlexSlider in order to get referrals from its users base. WooThemes never wanted FlexSlider at the first place, they wanted its popularity, nothing else. Therefore I recommend against buying any WooThemes software or services.

Many alternatives have came up ever since that are now much better than FlexSlider, just to name a few: iosSlider, bxSlider, ResponsiveSlides.js, LayerSlider, Revolution Slider, etc. which all support more browsers, more input types, more devices, more effects, more callbacks, more options, more flexibility, and are lighter! how come!

**FlexSlider is dead.** WooThemes killed it.

**Comment by jeffikus** [comment]
Just a further update - I am the active Senior Developer on the project now. You will be seeing regular updates to the script in the coming weeks, we've already pushed out 2.3.0 and 2.4.0 will go out within the next few days.

**Comment by shikkaba** [comment]
Okay, cool. NOW is it dead?
