### ISSUE TITLE
Add RTL Support

### ISSUE THREAD

**Issue by mattyza** [woothemes/FlexSlider#756]
It would be useful if FlexSlider's JavaScript and CSS files catered for RTL (right to left) language.

This could be detected using the `dir` parameter, often added to the `<html>` tag, or whichever is the standard method for detecting an RTL language page.

**Comment by NabiKAZ** [comment]
Please marge this patch into master branch of the project for core support RTL.

**Comment by jeffikus** [comment]
@NabiKAZ there already is an open RTL patch #1374 for the 2.7.0 cycle.

**Comment by jeffikus** [comment]
Merged https://github.com/woothemes/FlexSlider/pull/1561 :)
