### ISSUE TITLE
slider.getTarget should respect animationLoop

### ISSUE THREAD

**Issue by knupska** [woothemes/FlexSlider#811]
I suspect the looping issues that people are experiencing using `animationLoop:false` with both the next/prev arrows and touch navigation, could be rectified by having the `slider.getTarget` function respect the `animationLoop` setting.

So changing:

```javascript
slider.getTarget = function(dir) {
  slider.direction = dir;
  if (dir === "next") {
    return (slider.currentSlide === slider.last) ? 0 : slider.currentSlide + 1;
  } else {
    return (slider.currentSlide === 0) ? slider.last : slider.currentSlide - 1;
  }
}
```
to something like:

```javascript
slider.getTarget = function(dir) {
  slider.direction = dir;
  if (dir === "next") {
    return (slider.currentSlide !== slider.last) ? slider.currentSlide + 1 :
           (slider.vars.animationLoop) ? 0 :
           slider.currentSlide;
  } else {
    return (slider.currentSlide !== 0) ? slider.currentSlide - 1 :
           (slider.vars.animationLoop) ? slider.last :
           slider.currentSlide;
  }
}
```

**Comment by mpdude** [comment]
@jeffikus Hm, simply closing this without a comment?

**Comment by jeffikus** [comment]
Hi @mpdude - have you checked with the latest version? https://github.com/woothemes/FlexSlider/releases/latest also, we announced the closure of http://develop.woothemes.com/flexslider/2015/03/18/flexslider-future-forecasting/
