### ISSUE TITLE
Sync'd Carousel Won't Return to First Slide

### ISSUE THREAD

**Issue by friedbyte** [woothemes/FlexSlider#818]
Hi,

Is there a trick to stopping at the first slide after the animation loop completes? I've tried a lot of different combinations of things, but I'm not sure how to make the carousel thumb go back to slide one after the loop completes. Here is a link to the slideshow, you'll notice the thumbs do not go back to slide one. http://ipsen.friedbyte.com/slideshow.html

Thanks,

Nate

**Comment by hasbi001** [comment]
Hallo Friend 

thank you for solving and works for me, but how to put that function in the before option?

thank you
