### ISSUE TITLE
How to display caption

### ISSUE THREAD

**Issue by thehung2224** [woothemes/FlexSlider#819]
I saw many examples in your site but i can't find example with caption. So how can i enable this feature? Hope you reply soon. Thank you :)

**Comment by kennedysgarage** [comment]
I know I am late to the party, but figured I would help the next person that stumbled upon this page.

.flex-caption{
  background-color: rgba(0,0,0,0.3);
  bottom: 0;
  color: #fff;
  left: 0;
  margin: 0;
  padding: 10px;
  position: absolute;
  right: 0;
  text-align: center;
}
