### ISSUE TITLE
Rename CSS to flexslider-min.css.

### ISSUE THREAD

**Issue by grayghostvisuals** [woothemes/FlexSlider#828]
Just for reference this is the file in question [https://github.com/woothemes/FlexSlider/blob/master/flexslider.css](https://github.com/woothemes/FlexSlider/blob/master/flexslider.css).

If you want this to be the minified file then please rename it to ``flexslider-min.css``. If possible it would be cool to have an unminified version as well -or- at least another CSS file that doesn't have the CSS written on one line.

**Comment by mattyza** [comment]
Thanks @grayghostvisuals.

We'll be optimising the CSS, and minifying it, once our Grunt/Gulp script is in place.

cc @jeffikus.
