### ISSUE TITLE
IOS7 css transitions

### ISSUE THREAD

**Issue by thomasvankerckvoorde** [woothemes/FlexSlider#853]
All my sites that use FlexSlider on iOS7 (Chrome and Safari) seem to have issues when you swipe on the '.flexslider' container. When you for example swipe down (on your container), hold it and then move left or right it moves your slide and after that it just seems to lock up.

It seems to be an issue with CSS transitions in iOS7, 'useCSS': false, seems to fix it.

**Comment by drywall** [comment]
FWIW, I've encountered this issue too. The "webkitTransitionEnd transitionend" event definitely isn't firing, dunno why. Setting useCSS to false fixes the issue as it bypasses CSS transitions and thus doesn't need to listen for those events.

**Comment by LittleHendrix** [comment]
I was having the same issue on iOS8 mobile safari. added what @Semmie suggested and the problem seems to have gone away! Thank you!
