### ISSUE TITLE
Flexslider doesn't load on jQuery .ajax refresh in "success"

### ISSUE THREAD

**Issue by 5zymon** [woothemes/FlexSlider#897]
This is my html 

    <div class="productslider">
    <ul>
    <li></li > //slide 1
    <li></li> //slide 2
    <li></li> //slide 3
    </ul>
    </div>

I use this to call Flexslider on page

        jQuery('.productslider').flexslider({
          animation: "slide",
          animation: "fade",
          controlNav: "thumbnails",
          slideshow: false,
          start: function(slider){
            console.log('flexlider started');
          }
        });

and this works too. 

Now I refresh content of the .productslider div with this ajax

    jQuery.ajax({
      type: "POST",
      url: ....
      dataType: "json",
      data: {.... },
      success: function(data) {
    JQuery('.productslider").htm('<ul><li></li></ul>');
            jQuery('.productslider').flexslider({
          animation: "slide",
          animation: "fade",
          controlNav: "thumbnails",
          slideshow: false,
          start: function(slider){
            console.log('flexlider started');
          }
        });
    },
    failure {
    }
    });

Flexslider works when I open the page. Now with the the ajax query I am changing content of the div container, and it actually changes like I want it to. But even though flexslider is called again in the success, it doesnt load again and I end with modified div, but no images :-(

**Comment by jaydip321** [comment]
i am facing an issue very similar to you issue.
please help me to solve if you make it way.

Thanks
