### ISSUE TITLE
Basic Carousel not work with "fade" animation?

### ISSUE THREAD

**Issue by hoangnm89** [woothemes/FlexSlider#912]
I downloaded zip file of version: v2.2.0. I viewed file: demo\basic-carousel.html
I tried to change an option animation form: slide -> fade. Then it rollback to base slide(one image per page), i want to all image per page fade when i press next button.

$('.flexslider').flexslider({
        animation: "fade",
        animationLoop: false,
        itemWidth: 210,
        itemMargin: 50,
        pausePlay: true,
        start: function(slider){
          $('body').removeClass('loading');
        }
      });

**Comment by jupitercow** [comment]
This still doesn't work.
