### ISSUE TITLE
Mousewheel direction animation

### ISSUE THREAD

**Issue by drivebass** [woothemes/FlexSlider#916]
Is the mousewheel function supposed to support animating direction like the next previous navs? Meaning when you scroll up slides animate up and when down slides animate down. Different directions for up or down scroll. Because I only get the same animating direction for both scroll up or down while the prev next nav controls move the slides to different directions as they were supposed to. Does anyone has the same issue with mousewheel control?

**Comment by bharatbondu** [comment]
Yes, I'm facing the same issue. Needs to be fixed!
