### ISSUE TITLE
controlNav: "thumbnails", hangs the browser

### ISSUE THREAD

**Issue by dipakdotyadav** [woothemes/FlexSlider#917]
I am using the below code to show flex slide show the code is taken from demo/index.html
```javascript
$(window).load(function(){
      $('.flexslider').flexslider({
        animation: "slide",
        //controlNav: "thumbnails",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });
      $slider = $(".flexslider").data('flexslider');

      $slider.addSlide('<li><img src="images/kitchen_adventurer_lemon.jpg" /></li>', 1)
      
    });
```

when the code (controlNav: "thumbnails",)  is uncommented my browser gets hanged and the page become unresponsive, i need to kill the page forcefully

i am using chrome Version 31.0.1650.48

**Comment by wpaholic** [comment]
lol, i have encountered this issue today while implementing the Woocommerce gallery slider.
