### ISSUE TITLE
animationLoop: false Does Not work with latest version of Flexslider. 

### ISSUE THREAD

**Issue by fthrwght** [woothemes/FlexSlider#932]
The animationLoop setting in the live Basic Carousel demo ( found here: http://flexslider.woothemes.com/basic-carousel.html ) is not consistent with the latest version of Flexslider. 

To test this, open the Basic Carousel demo included in the latest version of Flexslider and notice that the animation loop is continuous even though the settings indicate "animationLoop: false" 

The live demo appears to be using an older version of Flexslider where that setting works as intended. If you click the next/previous buttons there, once you get to the end, the slider correctly stops sliding.

**Comment by grisuno** [comment]
i comented de lines u say, but, the slide is like animationLoop is set to true, i desesperated. please

**Comment by koiyu** [comment]
Still there: https://github.com/woothemes/FlexSlider/blob/master/jquery.flexslider.js#L677

Changing line 677 from:
```javascript
      if (!slider.vars.animationLoop && target !== slider.currentSlide) {
```

to
```javascript
      if (slider.vars.animationLoop && target !== slider.currentSlide) {
```

works adequately for me (ie. get rid of the `!`). Now both animationLoop = true and animationLoop = false cases work as expected.

**Comment by mgustavs** [comment]
I desperately try to stop my flexslider from looping but it does not care if 'true' or 'false' after animationLoop and loops on anyway... 

if (slider.vars.animationLoop && target !== slider.currentSlide) {     did not dothe trick...
