### ISSUE TITLE
Not shown icons nav Flexlider2

### ISSUE THREAD

**Issue by JMcase** [woothemes/FlexSlider#936]
I downloaded Flexlider 2 the next and previus icons are not shown.
Could help me?
Thanks

**Comment by kubik101** [comment]
In my case it was to do with the error you see in Firefox when you view console in Web Developer Tools.

See error.

13:35:17.415 downloadable font: download failed (font-family: "flexslider-icon" style:normal weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: file:my/local/paht/demo/fonts/webfonts/flexslider-icon.ttf1 demo.css:51:12

Once you have all your files on your server it will work.

Viewing offline/locally is the issue (only in FireFox).

**Comment by danicotillas** [comment]
Just try to add to the CSS class > font-family: FontAwesome; 
and see if it works. It does to me.

**Comment by Joshuasony** [comment]
In my case, this solved it for me:
```
/* Icon Fonts
*********************************/
/* Font-face Icons */
@font-face {
	font-family: 'flexslider-icon';
	src: url('fonts/flexslider-icon.eot');
	src: url('fonts/flexslider-icon.eot?#iefix') format('embedded-opentype'),
		url('fonts/flexslider-icon.woff') format('woff'),
		url('fonts/flexslider-icon.ttf') format('truetype'),
		url('fonts/flexslider-icon.svg#flexslider-icon') format('svg');
	font-weight: normal;
	font-style: normal;
}
```

Had to manually set the src for the font-family.
