### ISSUE TITLE
How to continue to Flexsilder after the Youtube Video finishes.

### ISSUE THREAD

**Issue by thainguyenit** [woothemes/FlexSlider#943]
Hi All
I tried it for videos and images. There is a bug

- After The video finishes (not click on pause button of video player) but the slider don't continues to sliding.

My code: http://focode.com/demo/slider/index-video07.html
please help me to fix this bug, thank you.

**Comment by chrissands** [comment]
What did you do to fix this? Your code isn't hosted anymore.
