### ISSUE TITLE
When using a carousel synced with a second slider, moving from last to first doesn't update the carousel

### ISSUE THREAD

**Issue by mikehdt** [woothemes/FlexSlider#946]
There appears to be an issue with having two FlexSliders - one normal, and a second as a carousel synced as navigation. If you move the large slider from its last slide to the first, the synced carousel does not update until you move to the second item in the large slider. The line that causes issue seems to be this one (currently line 654):

```javascript
if (Math.ceil((target + 1)/slider.visible) - 1 !== slider.currentSlide && target !== 0) {
```

Removing the `&& target !== 0` seems to fix the issue, but I'm not sure what effect it may have on other configurations.

**Comment by zanematthew** [comment]
@NukaPunk This fix does work, but maybe going to first slide to the last isn't expected? As its only expected to loop clockwise and not counter clockwise?

@jeffikus What would be the expected behavior.
