### ISSUE TITLE
Play/Pause button still showing when there's only one slide in Flexslider Views Slideshow.

### ISSUE THREAD

**Issue by hackish** [woothemes/FlexSlider#951]
I'm using Flexslider Views Slideshow in Drupal 7 and some of the slideshows I use have just a single image. The pager does hide itself like it's supposed to when viewing those single image slides but the pause/play controls is still showing up.

How do I go about hiding the pause/play controls for single image slideshows as well?

**Comment by aastrong** [comment]
I know this is a year late, but if your still wondering, you can see the issue raised here.
https://www.drupal.org/node/2219435

If in drupal, the patch file https://www.drupal.org/files/issues/pause_1_slide-flexslider-2219435-1.patch

```
 if ($(optionset.selector, this).length < 2) {
        // Remove pause button if slides are less then two.
        optionset.pausePlay = false;
      }
```


Cheers.

**Comment by aastrong** [comment]
I would assume that it might be slightly different if a site is not in drupal, but should be similar.
