### ISSUE TITLE
Firefox 26.0 onTouchStart vs ontouchstart

### ISSUE THREAD

**Issue by ghost** [woothemes/FlexSlider#958]
Flexslider 2.2.0
After update of FF to Version 26.0 my FlexSlider doesn't work correctly. I get error "ReferenceError: onTouchStart is not defined jquery.flexslider.js:397" with settings
animation: "slide", touch: true

When starting with a half sized browser window and 2 images the first image is scaled down. Everything seems to be OK. But when I enlarge the window to full size I see more than 2 images side by side and they don't react responsive. The clones aren't hidden.

Setting touch:false: works.

With touch:true I changed line 397 of jquery.flexslider.js from

el.addEventListener('touchstart', onTouchStart, false);

to (see lower case):

el.addEventListener('touchstart', ontouchstart, false);

The above mentioned error is gone and after some quick tests it looks like this fix works on FIREFOX (no further testing with other browsers!!).

**Comment by pribilinskiy** [comment]
@miketaylr Please update the fix for v2.3.0

**Comment by miketaylr** [comment]
@pribilinskiy happy to do so. @jeffikus: is there any chance of this getting merged into master?

**Comment by miketaylr** [comment]
I just ran into this on another site in the wild (http://mobile.suntory.co.jp). Let me update my patch against master and send a PR.

**Comment by miketaylr** [comment]
Just rebased my PR @ #986 against the latest master.

**Comment by jeffikus** [comment]
I did a new pull request #1335 for this on release branch 2-5-0 so I can further test this.

**Comment by miketaylr** [comment]
Great! Thanks @jeffikus

**Comment by jeffikus** [comment]
@miketaylr once again I'm really grateful for your pull request and contribution to the project :) super happy when I get stuff like this! :dancers:
