### ISSUE TITLE
Multiple sliders don't work in IE7 - have solution

### ISSUE THREAD

**Issue by kg69design** [woothemes/FlexSlider#981]
Multiple sliders don't work in IE7, only the first is shown. This bug is in version 2.2.2 but is not in 2.1. I compared both scripts line-by-line and found the code, that is responsible for this bug. Here it is in jquery.flexslider.js:
```js
slider.find("img").attr("draggable", "false");
```
In jquery.flexslider-min.js it is:
```js
r.find("img").attr("draggable","false");
```
Deleting this line fix the problem. Glad it helps. Thanks for good plugin.

**Comment by jeffikus** [comment]
IE7 is deprecated and will not be supported going forward.
