### ISSUE TITLE
Flexslider Navigation is not working in IE 11

### ISSUE THREAD

**Issue by shippoFox** [woothemes/FlexSlider#997]
Flexslider is visible, but the navigation buttons on the side and the dots on the bottom do not work to navigate between slides, and the slides do not automatically play. It works in all other browsers that I tested. Just IE 11 is the problem.

**Comment by SoniaDev** [comment]
I used jquery.flexslider.js but the navigation buttons is not working in IE 11.0.6900!!!

**Comment by Komal108** [comment]
thanks @umarananda !!
I tried a lot for this, but no luck, after changing the two lines as u mentioned, its working now.
and the strange thing thing, no console errors on ie11, very difficult to get into this solution

thanks again :)
